
#ifndef	_SoundLibErrorString_h_
#define	_SoundLibErrorString_h_

/*
char	g_pszErrorString[][100]	=	{
	"SOUND_ERROR_NOERRORR",
	"SOUND_ERROR_ALREADY_INITIALIZED",
	"SOUND_ERROR_INVALID_ARGUMENT",
	"SOUND_ERROR_MILES_STARTUP_FAILED",
	"SOUND_ERROR_BGMDRIVER_STARTUP_FAILED",
	"SOUND_ERROR_BGMDRIVER_NOT_LOADED",
	"SOUND_ERROR_INVALID_FILENAME"



};
*/

#endif