#ifndef _DEFINE_H
#define	_DEFINE_H

const DWORD DEFAULT_HEADER_SIZE		= 2;
const DWORD DEFAULT_MESSAGE_LENGTH	= 3;
const DWORD MAX_IP_LENGTH		= 32;
const DWORD DEFAULT_QUEUE_NUM	= 128;
const DWORD MAX_SERVER_BUFFER_SIZE		= 512000;
const DWORD MAX_USER_BUFFER_SIZE		= 128000;
const DWORD MAX_PACKET_SIZE		= 51200;
const DWORD MAX_USER_NUM		= 4000;
const DWORD MAX_SERVER_NUM		= 1000;
const DWORD MAX_CHAT_MSG_LENGHT = 255;
const int DEFAULT_TRANSFER_RECV_SIZE = 8192;
const int DEFAULT_TRANSFER_SEND_SIZE = 8192;
const DWORD MAX_UDP_BUFFER_SIZE = 1024;
const DWORD MIN_PROCESS_TIME = 30;
const DWORD MAX_MSGQUE_SIZE = 5120000;

#endif

