/*main title*/
	WINDOW_ID(MT_LOGODLG),
	WINDOW_ID(MT_LOGINDLG),
	WINDOW_ID(MT_BIDLG),
	WINDOW_ID(MT_COPYDLG),
	WINDOW_ID(MT_OKBTN),
	WINDOW_ID(MT_CANCELBTN),
	WINDOW_ID(MT_IDEDITBOX),
	WINDOW_ID(MT_PWDEDITBOX),
	WINDOW_ID(MT_PNSTATIC),	// 2008. 3. 18. CBH - 보안번호 박스
	WINDOW_ID(MT_LISTCOMBOBOX),	// magi82
	WINDOW_ID(MT_LISTCOMBOBOXBTN),// magi82
	WINDOW_ID(MT_ENDBTN),
	WINDOW_ID(MT_OPTIONBTN),			
	WINDOW_ID(MT_ADDACCOUNTBTN),		// 10
	WINDOW_ID(MT_MAINTITLEDLG),

	// dynamic
	WINDOW_ID(MT_DYNAMICDLG),
	WINDOW_ID(MT_DYNAMICPWDEDITBOX),
	WINDOW_ID(MT_DYNAMICOKBTN),
	WINDOW_ID(MT_DYNAMICEXITBTN),
	WINDOW_ID(MT_STC_DYNAMICID),
	WINDOW_ID(MT_STC_COORD),
	WINDOW_ID(MT_STC_COORD_MAT),

/*char select*/
	WINDOW_ID(CS_CHAR1PUSHBTN),			
	WINDOW_ID(CS_CHAR2PUSHBTN),			// 20
	WINDOW_ID(CS_CHAR3PUSHBTN),
	WINDOW_ID(CS_CHAR4PUSHBTN),
	WINDOW_ID(CS_CHAR1NAMESTATIC),
	WINDOW_ID(CS_CHAR2NAMESTATIC),
	WINDOW_ID(CS_CHAR3NAMESTATIC),
	WINDOW_ID(CS_CHAR4NAMESTATIC),
	WINDOW_ID(CS_CHAR1LEVELSTATIC),

	WINDOW_ID(CS_CHAR2LEVELSTATIC),
	WINDOW_ID(CS_CHAR3LEVELSTATIC),
	WINDOW_ID(CS_CHAR4LEVELSTATIC),		// 30
	WINDOW_ID(CS_CHAR1LOCSTATIC),
	WINDOW_ID(CS_CHAR2LOCSTATIC),
	WINDOW_ID(CS_CHAR3LOCSTATIC),
	WINDOW_ID(CS_CHAR4LOCSTATIC),
	WINDOW_ID(CS_CHARSELECTBTN),
	WINDOW_ID(CS_CHARCREATEBTN),
	WINDOW_ID(CS_CHARDELETEBTN),

	WINDOW_ID(CS_CHARCANCELBTN),		
	WINDOW_ID(CS_CHARSELECTDLG),
	WINDOW_ID(CSID_CharSelectInfoDlg1),	// 40
	WINDOW_ID(CSID_CharSelectInfoDlg2),
	WINDOW_ID(CSID_CharSelectInfoDlg3),
	WINDOW_ID(CSID_CharSelectInfoDlg4),
	WINDOW_ID(CSID_CharLevel1),
	WINDOW_ID(CSID_CharLevel2),
	WINDOW_ID(CSID_CharLevel3),
	WINDOW_ID(CSID_CharLevel4),

	WINDOW_ID(CSID_CharName1),
	WINDOW_ID(CSID_CharName2),
	WINDOW_ID(CSID_CharName3),			// 50
	WINDOW_ID(CSID_CharName4),
	WINDOW_ID(MT_FIRSTCHOSEBTN),
	WINDOW_ID(MT_SECONDCHOSEBTN),
	WINDOW_ID(MT_THIRDCHOSEBTN),
	WINDOW_ID(MT_FOURTHCHOSEBTN),
	WINDOW_ID(MT_FIFTHCHOSEBTN),
	WINDOW_ID(CSID_MessageBox),
	WINDOW_ID(CSID_MessageTxt),	

/*AE¡¤¨￢AI ¡iefA¡E  */

/**/
	WINDOW_ID(CMID_MessageBox),
	WINDOW_ID(CMID_MessageTxt),
	WINDOW_ID(CMID_NONableName),		// 60
	WINDOW_ID(CMID_SUCCESSMakeChar),
	WINDOW_ID(CMID_FAILMakeChar),
/*char make*/
/*
	WINDOW_ID(CMID_IDEDITBOX),
	WINDOW_ID(CMID_OverlapCheck),

	WINDOW_ID(CMID_JobType),
	WINDOW_ID(CMID_SexType),
	WINDOW_ID(CMID_ClothType),

	WINDOW_ID(CMID_HairType),
	WINDOW_ID(CMID_FaceType),
	WINDOW_ID(CMID_BootType),
	WINDOW_ID(CMID_WeaponType),
	WINDOW_ID(CMID_StartArea),
	WINDOW_ID(CMID_CharMake),
	WINDOW_ID(CMID_CharCancel),

	WINDOW_ID(CMID_PJobType),	//?
	WINDOW_ID(CMID_PSexType),
	WINDOW_ID(CMID_PBodyType),	


	WINDOW_ID(CMID_PStartArea),
	WINDOW_ID(CMID_ManFaceType),
	WINDOW_ID(CMID_WomanFaceType),
	WINDOW_ID(CMID_ManHairType),
	WINDOW_ID(CMID_WomanHairType),
	WINDOW_ID(CMID_Height),
	WINDOW_ID(CMID_Width),
	*/
	WINDOW_ID(CMID_AttribType),
	WINDOW_ID(CMID_SexType),
	WINDOW_ID(CMID_ManHairType),
	WINDOW_ID(CMID_WomanHairType),
	WINDOW_ID(CMID_ManFaceType),
	WINDOW_ID(CMID_WomanFaceType),
	WINDOW_ID(CMID_ClothType),
	WINDOW_ID(CMID_BootType),			// 70
	WINDOW_ID(CMID_WeaponType),
	
	WINDOW_ID(CMID_IDEDITBOX),
	WINDOW_ID(CMID_OverlapCheck),
	WINDOW_ID(CMID_CharMake),
	WINDOW_ID(CMID_CharCancel),
	WINDOW_ID(CMID_Height),
	WINDOW_ID(CMID_Width),
	
	WINDOW_ID(CMID_WeaponLeft),
	WINDOW_ID(CMID_WeaponRight),
	WINDOW_ID(CMID_BootLeft),			// 80
	WINDOW_ID(CMID_BootRight),
	WINDOW_ID(CMID_ClothLeft),
	WINDOW_ID(CMID_ClothRight),
	WINDOW_ID(CMID_FaceLeft),
	WINDOW_ID(CMID_FaceRight),
	WINDOW_ID(CMID_HairLeft),
	WINDOW_ID(CMID_HairRight),
	WINDOW_ID(CMID_SexLeft),
	WINDOW_ID(CMID_SexRight),
	WINDOW_ID(CMID_AttribLeft),			// 90
	WINDOW_ID(CMID_AttribRight),

/*Aⓒø￠￢?A¡E*/
	WINDOW_ID(CI_CHARDLG),
	WINDOW_ID(CI_MUNPAMARK),
	WINDOW_ID(CI_CHARMUNPA),
	WINDOW_ID(CI_CHARJIKWE), 
	WINDOW_ID(CI_CHARFAME),

	WINDOW_ID(CI_CHARBADFAME),
	WINDOW_ID(CI_CHARNAME), 
	WINDOW_ID(CI_CHARSTAGE), 
	WINDOW_ID(CI_CHARGENGOAL),			// 100
	WINDOW_ID(CI_CHARSIMMAK), 
	WINDOW_ID(CI_CHARDEX), 
	WINDOW_ID(CI_CHARSTA), 
	WINDOW_ID(CI_CHARLEVEL),
	WINDOW_ID(CI_CHAREXPPERCENT),
	WINDOW_ID(CI_CHARPOINT),
	WINDOW_ID(CI_CHARJOB),

	WINDOW_ID(CI_CHARATTACK), 
	WINDOW_ID(CI_LONGATTACK), 	
	WINDOW_ID(CI_CHARDEFENSE),			// 110
	WINDOW_ID(CI_CHARKYEONGKONG),
	WINDOW_ID(CI_CHARMOVE),
	WINDOW_ID(CI_CHARLIFE),
	WINDOW_ID(CI_CHARNAERYUK),

#ifdef _JAPAN_LOCAL_
	WINDOW_ID(CI_CHARHWA),
	WINDOW_ID(CI_CHARTO),
	WINDOW_ID(CI_CHARKUM),
	WINDOW_ID(CI_CHARSU),
	WINDOW_ID(CI_CHARMOK),

	WINDOW_ID(CI_CHARATTRIB),
	WINDOW_ID(CI_CHARHWAATTACK),
	WINDOW_ID(CI_CHARTOATTACK),
	WINDOW_ID(CI_CHARKUMATTACK),
	WINDOW_ID(CI_CHARSUATTACK),
	WINDOW_ID(CI_CHARMOKATTACK),
#else
	WINDOW_ID(CI_CHARHWA),
	WINDOW_ID(CI_CHARSU),
	WINDOW_ID(CI_CHARMOK),	
	WINDOW_ID(CI_CHARKUM),
	WINDOW_ID(CI_CHARTO),
#endif

	WINDOW_ID(CI_SPCHARNAME),			// 120
	WINDOW_ID(CI_CRITICAL),
	WINDOW_ID(CI_DISTANCE),
	WINDOW_ID(CI_HOSINDEFENSE),
	WINDOW_ID(CI_EXPPOINTGUAGE),
	WINDOW_ID(CI_GENGOL_POINT),
	WINDOW_ID(CI_SIMMEK_POINT),
	WINDOW_ID(CI_MINCHUB_POINT),
	WINDOW_ID(CI_CHERYUK_POINT),
	WINDOW_ID(CI_GENGOL_POINT2),
	WINDOW_ID(CI_SIMMEK_POINT2),		// 130
	WINDOW_ID(CI_MINCHUB_POINT2),
	WINDOW_ID(CI_CHERYUK_POINT2),
	WINDOW_ID(CI_DEFENCE_HWA),
	WINDOW_ID(CI_DEFENCE_SU),
	WINDOW_ID(CI_DEFENCE_MOK),
	WINDOW_ID(CI_DEFENCE_KUM),
	WINDOW_ID(CI_DEFENCE_TO),

	// 06. 02. 내정보창 팁보기 추가 - 이영준
	WINDOW_ID(CI_BESTTIP),

	WINDOW_ID(TIPBROWSER_DLG),
	WINDOW_ID(TB_STATE_PUSHUP1),
	WINDOW_ID(TB_STATE_PUSHUP2),
	WINDOW_ID(TB_STATE_PUSHUP3),
	WINDOW_ID(TB_STATE_PUSHUP4),
	WINDOW_ID(TB_STATE_PO),
	WINDOW_ID(TB_STATE_AG),
	WINDOW_ID(TB_STATE_HE),
	WINDOW_ID(TB_STATE_MA),
	WINDOW_ID(TB_CANCELBTN),
	
/*ⓒo¡i¡ÆⓒªA¡E22*/
	WINDOW_ID(MGI_MUGONGSURYUNDLG),
		WINDOW_ID(MGI_MUGONGBTN),
		WINDOW_ID(MGI_SURYUNBTN),		// 140

		WINDOW_ID(MGI_SHEET1),	

			WINDOW_ID(MGI_MUGONG_PUSHUP1),
			WINDOW_ID(MGI_MUGONG_PUSHUP2),
			WINDOW_ID(MGI_JINBUB_PUSHUP3),
			WINDOW_ID(MGI_MUGONG_TITAN_PUSHUP),	// magi82 - Titan(070910) 타이탄 무공업데이트

			WINDOW_ID(MGI_MUGONG1_GRID1),
			WINDOW_ID(MGI_MUGONG1_GRID2),
			WINDOW_ID(MGI_JINBUB_GRID),
			WINDOW_ID(MGI_TITAN_GRID),			// magi82 - Titan(070910) 타이탄 무공업데이트
			
			WINDOW_ID(MGI_MUGONGJINBUB_EXP_GUAGE),
			WINDOW_ID(MGI_MUGONGJINBUB_EXP_STATIC),
			WINDOW_ID(MGI_MUGONGJINBUB_WEAR),		// 150			
			WINDOW_ID(MGI_MUGONGJINBUB_NAME_STATIC),
			WINDOW_ID(MGI_MUGONGJINBUB_LEVEL_STATIC),
			
#ifdef _JAPAN_LOCAL_
		WINDOW_ID(MGI_MUGONGDLG),

			WINDOW_ID(MGI_MUGONG_WEAR),
			WINDOW_ID(MGI_MUGONG_GRID),
			WINDOW_ID(MGI_MUGONG_NAME_STATIC),
			WINDOW_ID(MGI_MUGONG_LEVEL_STATIC),
			WINDOW_ID(MGI_MUGONG_EXP_GUAGE),
			WINDOW_ID(MGI_MUGONG_EXP_STATIC),

			WINDOW_ID(MGI_JINBUB_WEAR),
			WINDOW_ID(MGI_JINBUB_NAME_STATIC),
			WINDOW_ID(MGI_JINBUB_LEVEL_STATIC),
			WINDOW_ID(MGI_JINBUB_EXP_GUAGE),
			WINDOW_ID(MGI_JINBUB_EXP_STATIC),

		WINDOW_ID(MGI_SURYUNDLG),
#elif defined _HK_LOCAL_
		WINDOW_ID(MGI_MUGONGDLG),

			WINDOW_ID(MGI_MUGONG_WEAR),
			WINDOW_ID(MGI_MUGONG_GRID),
			WINDOW_ID(MGI_MUGONG_NAME_STATIC),
			WINDOW_ID(MGI_MUGONG_LEVEL_STATIC),
			WINDOW_ID(MGI_MUGONG_EXP_GUAGE),
			WINDOW_ID(MGI_MUGONG_EXP_STATIC),

			WINDOW_ID(MGI_JINBUB_WEAR),
			WINDOW_ID(MGI_JINBUB_NAME_STATIC),
			WINDOW_ID(MGI_JINBUB_LEVEL_STATIC),
			WINDOW_ID(MGI_JINBUB_EXP_GUAGE),
			WINDOW_ID(MGI_JINBUB_EXP_STATIC),

		WINDOW_ID(MGI_SURYUNDLG),
#elif defined _TL_LOCAL_
		WINDOW_ID(MGI_MUGONGDLG),

			WINDOW_ID(MGI_MUGONG_WEAR),
			WINDOW_ID(MGI_MUGONG_GRID),
			WINDOW_ID(MGI_MUGONG_NAME_STATIC),
			WINDOW_ID(MGI_MUGONG_LEVEL_STATIC),
			WINDOW_ID(MGI_MUGONG_EXP_GUAGE),
			WINDOW_ID(MGI_MUGONG_EXP_STATIC),

			WINDOW_ID(MGI_JINBUB_WEAR),
			WINDOW_ID(MGI_JINBUB_NAME_STATIC),
			WINDOW_ID(MGI_JINBUB_LEVEL_STATIC),
			WINDOW_ID(MGI_JINBUB_EXP_GUAGE),
			WINDOW_ID(MGI_JINBUB_EXP_STATIC),

		WINDOW_ID(MGI_SURYUNDLG),
#endif // _JAPAN_LOCAL_

		
		WINDOW_ID(MGI_SHEET2),
			WINDOW_ID(MGI_SURYUN_PUSHUP1),
			WINDOW_ID(MGI_SURYUN_PUSHUP2),
			WINDOW_ID(MGI_SURYUN_PUSHUP3),
			WINDOW_ID(MGI_SURYUN_PUSHUP4),
			WINDOW_ID(MGI_SURYUN_PUSHUP5),
			WINDOW_ID(MGI_SURYUN1_GRID),
			WINDOW_ID(MGI_SURYUN2_GRID),
			WINDOW_ID(MGI_SURYUN3_GRID),	// 160	

			WINDOW_ID(MGI_SURYUN4_GRID),
			WINDOW_ID(MGI_SURYUN5_GRID),
			WINDOW_ID(MGI_NEEDSURYUN_EXP_STATIC),	//@￠?a¡¾￠￢¨uo¡¤AA￠®
			WINDOW_ID(MGI_SURYUN_EXP_STATIC),	//@¨uo¡¤AA￠®
			WINDOW_ID(MGI_SURYUN_BTN),	//@¨uo¡¤A
			WINDOW_ID(MGI_SKPOINTREDIST_BTN),
/*	
		WINDOW_ID(MGI_MUGONGDLG),
	
		WINDOW_ID(MGI_MUGONG_WEAR),
		WINDOW_ID(MGI_MUGONG_GRID),
		WINDOW_ID(MGI_MUGONG_NAME_STATIC),
		WINDOW_ID(MGI_MUGONG_LEVEL_STATIC),
		WINDOW_ID(MGI_MUGONG_EXP_STATIC),
		WINDOW_ID(MGI_MUGONG_EXP_GUAGE),
	
		WINDOW_ID(MGI_JINBUB_WEAR),
		WINDOW_ID(MGI_JINBUB_GRID),
		WINDOW_ID(MGI_JINBUB_NAME_STATIC),
		WINDOW_ID(MGI_JINBUB_LEVEL_STATIC),
		WINDOW_ID(MGI_JINBUB_EXP_STATIC),
		WINDOW_ID(MGI_JINBUB_EXP_GUAGE),
	
		WINDOW_ID(MGI_SIMBUB_WEAR),
		WINDOW_ID(MGI_SIMBUB_GRID),
		WINDOW_ID(MGI_SIMBUB_NAME_STATIC),
		WINDOW_ID(MGI_SIMBUB_LEVEL_STATIC),
		WINDOW_ID(MGI_SIMBUB_EXP_STATIC),
		WINDOW_ID(MGI_SIMBUB_EXP_GUAGE),*/
	

/*￠￢¨­AIAIAI¨¡aAI¨o¨￢10*/
	WINDOW_ID(MI_CHARBTN), 
	WINDOW_ID(MI_EXCHANGEBTN), 
	WINDOW_ID(MI_INVENTORYBTN), 
	WINDOW_ID(MI_MUGONGBTN), 
	WINDOW_ID(MI_SKILLBTN),			// 170
	WINDOW_ID(MI_PARTYBTN),		

	WINDOW_ID(MI_MAINDLG), 
	WINDOW_ID(MI_BTN_SIZE),
	WINDOW_ID(MI_STC_TAIL),

	WINDOW_ID(MI_CHATEDITBOX),
	WINDOW_ID(MI_HEROGUAGE),
	WINDOW_ID(MI_OTHERGUAGE),

/*AI¨￢¡IAa￠￢￠c*/
	WINDOW_ID(IN_INVENTORYDLG),
	WINDOW_ID(IN_WEAREDDLG),
	WINDOW_ID(IN_TABBTN1),			// 180
	WINDOW_ID(IN_TABBTN2),
	WINDOW_ID(IN_TABBTN3),
	WINDOW_ID(IN_TABBTN4),
	WINDOW_ID(IN_SHOPITEMBTN),

	WINDOW_ID(IN_TABDLG1),
	WINDOW_ID(IN_TABDLG2),
	WINDOW_ID(IN_TABDLG3),
	WINDOW_ID(IN_TABDLG4),
	WINDOW_ID(IN_CREATESTREETSTALL),
	WINDOW_ID(IN_MONEYEDIT),		// 190
	WINDOW_ID(IN_SHOPITEMGRID),

/*A￠´¨¡AA¡E*/
	WINDOW_ID(CTI_DLG),
	WINDOW_ID(CTI_BTN_WHOLE),
	WINDOW_ID(CTI_BTN_PARTY),
	WINDOW_ID(CTI_BTN_MUNPA),
	WINDOW_ID(CTI_BTN_ALLMUNPA),
	WINDOW_ID(CTI_BTN_WORLD),
	WINDOW_ID(CTI_BTN_ALLWORLD1),

	WINDOW_ID(CTI_SHEET1), 
	WINDOW_ID(CTI_SHEET2),			// 200
	WINDOW_ID(CTI_SHEET3),
	WINDOW_ID(CTI_SHEET4),
	WINDOW_ID(CTI_SHEET5),
	WINDOW_ID(CTI_BTN_TALLER),
	WINDOW_ID(CTI_BTN_SMALLER),
	WINDOW_ID(CTI_BTN_OPTION),
	
//	WINDOW_ID(COI_DLG),
//	WINDOW_ID(COI_CB_OPTION01),
//	WINDOW_ID(COI_CB_OPTION02),
//	WINDOW_ID(COI_CB_OPTION03),
//	WINDOW_ID(COI_CB_OPTION04),
//	WINDOW_ID(COI_CB_OPTION05),
//	WINDOW_ID(COI_CB_OPTION06),
//	WINDOW_ID(COI_CB_OPTION07),
//	WINDOW_ID(COI_CB_OPTION08),
//	WINDOW_ID(COI_CB_OPTION09),
//	WINDOW_ID(COI_CB_OPTION10),
//	WINDOW_ID(COI_CB_OPTION11),
//	WINDOW_ID(COI_CB_OPTION12),

// LYJ 051017 구입노점상 추가

// 노점상 종류 선택 DLG
	WINDOW_ID(ST_OPTIONDLG),
	WINDOW_ID(SO_SELLBTN),
	WINDOW_ID(SO_BUYBTN),
	WINDOW_ID(SO_CANCELBTN),		// 210

// 구입 노점상 DLG
	WINDOW_ID(BS_STALLDLG),
	WINDOW_ID(BS_ICONGRID),
	WINDOW_ID(BS_TITLEEDIT),
	WINDOW_ID(BS_ENTER), 
	WINDOW_ID(BS_SELLBTN),
	WINDOW_ID(BS_SPBTN),
	WINDOW_ID(BS_MONEYEDIT),
	WINDOW_ID(BS_REGBTN),
	WINDOW_ID(BS_CLOSEBTN),

// 구입 아이템 등록 Dlg
	WINDOW_ID(BRS_STALLDLG),		// 220
	WINDOW_ID(BRS_CLOSEBTN),
	WINDOW_ID(BRS_TYPELIST),
	WINDOW_ID(BRS_ITEMLIST1),
	WINDOW_ID(BRS_ITEMLIST2), 
	WINDOW_ID(BRS_ITEMLIST3),
	WINDOW_ID(BRS_ITEMLIST4),
	WINDOW_ID(BRS_ITEMLIST5),
	WINDOW_ID(BRS_ITEMLIST6),
	WINDOW_ID(BRS_ITEMLIST7),
	WINDOW_ID(BRS_CLASSLIST),		// 230
	WINDOW_ID(BRS_VOLUMEEDIT),
	WINDOW_ID(BRS_MONEYEDIT),
	WINDOW_ID(BRS_REGBTN),
	WINDOW_ID(BRS_DELETEBTN), 
	WINDOW_ID(BRS_CLASSTEXT),
	WINDOW_ID(BRS_CLASSRECT1),
	WINDOW_ID(BRS_CLASSRECT2),
	WINDOW_ID(BRS_ITEMBIGRECT),
	WINDOW_ID(BRS_ITEMSMALLRECT1),
	WINDOW_ID(BRS_ITEMSMALLRECT2),	// 240
	
	// 노점상 검색창 by Stiner(8) ////////////////////////////////////////////
	WINDOW_ID(SFR_STALLFINDDLG),
		WINDOW_ID(SFR_TYPECOMBO),
		WINDOW_ID(SFR_TYPECOMBOBTN),

		WINDOW_ID(SFR_WEAPON_DETAILTYPECOMBO),
		WINDOW_ID(SFR_CLOTHES_DETAILTYPECOMBO),
		WINDOW_ID(SFR_ACCESSORY_DETAILTYPECOMBO),
		WINDOW_ID(SFR_POTION_DETAILTYPECOMBO),
		WINDOW_ID(SFR_MATERIAL_DETAILTYPECOMBO),
		WINDOW_ID(SFR_ETC_DETAILTYPECOMBO),
		WINDOW_ID(SFR_ITEMMALL_DETAILTYPECOMBO),
		WINDOW_ID(SFR_TITAN_DETAILTYPECOMBO),

		WINDOW_ID(SFR_DETAILTYPECOMBOBTN),
		WINDOW_ID(SFR_ITEMLIST),

		WINDOW_ID(SFR_CLASSLIST),

		WINDOW_ID(SFR_NAMESTATIC),
		WINDOW_ID(SFR_PRICESTATIC),

		WINDOW_ID(SFR_SEARCHBTN),
		WINDOW_ID(SFR_SEARCHALLBTN),
		WINDOW_ID(SFR_RESULTLIST),
		WINDOW_ID(SFR_RESULTPAGEBTN1),
		WINDOW_ID(SFR_RESULTPAGEBTN2),
		WINDOW_ID(SFR_RESULTPAGEBTN3),
		WINDOW_ID(SFR_RESULTPAGEBTN4),
		WINDOW_ID(SFR_RESULTPAGEBTN5),
		WINDOW_ID(SFR_RESULTPAGEBTNUP),
		WINDOW_ID(SFR_RESULTPAGEBTNDOWN),

		WINDOW_ID(SFR_PB_SELLMODE),
		WINDOW_ID(SFR_PB_BUYMODE),
	//////////////////////////////////////////////////////////////////////////

/*ⓒøea¡io*/
	WINDOW_ID(SSI_STALLDLG),
	WINDOW_ID(SSI_ICONGRID),
	WINDOW_ID(SSI_TITLEEDIT),
	WINDOW_ID(SSI_ENTER), 
	WINDOW_ID(SSI_BUYBTN),
	WINDOW_ID(SSI_REGISTBTN),
	WINDOW_ID(SSI_EDITBTN),
	WINDOW_ID(SSI_MONEYEDIT),
// LBS Aⓒ￢¡Æ￠® 03.09.18
	WINDOW_ID(SSI_REGISTENDBTN),
	WINDOW_ID(SSI_CLOSEBTN),		// 250

	// magi82(47)
	WINDOW_ID(SVD_STALLVIEWDLG),
		WINDOW_ID(SVD_ITEMGRID),
		WINDOW_ID(SVD_CLOSEBTN),

// LBS 03.10.16 Npc￠￥e¡icA¡E￠?￠® ¡ic￠?e----
	WINDOW_ID(NSI_LISTDLG),
	WINDOW_ID(NSI_SCRIPTDLG),
//----------------------------------	

// LBS 03.10.30 HelpA¡E￠?￠® ¡ic￠?e----
	WINDOW_ID(HI_LISTDLG),
	WINDOW_ID(HI_DLG),	
	WINDOW_ID(HI_EXPLANBTN),
	WINDOW_ID(HI_HANDLEBTN),	
	WINDOW_ID(HI_REARBTN),	
	WINDOW_ID(HI_ETCBTN),
	WINDOW_ID(HI_QnABTN),
	
//----------------------------------	

// LBS 03.11.07 ￥i￥i￠?iⓒoIA¡E￠?￠® ¡ic￠?e------
	WINDOW_ID(HSI_DLG),				// 260
	WINDOW_ID(HSI_NEXTBTN),
	WINDOW_ID(HSI_PREVBTN),
	WINDOW_ID(HSI_EXITBTN),
//-----------------------------------

/*¡ÆⓒªAeA¡E*/
	WINDOW_ID(CMI_CLOSEBTN), 
	WINDOW_ID(CMI_ALPHAGUAGE),
	WINDOW_ID(CMI_MONEYDLG),
	WINDOW_ID(CMI_MONEYOK),
	WINDOW_ID(CMI_MONEYCANCEL),	

	WINDOW_ID(CMI_MONEYSPIN),
	WINDOW_ID(CMI_MONEYSPINUP),		// 270
	WINDOW_ID(CMI_MONEYSPINDOWN),
	
/*¡ioaA¡E*/
	WINDOW_ID(DE_DEALERDLG),
	WINDOW_ID(DE_TABBTN1), 
	WINDOW_ID(DE_TABBTN2),
	WINDOW_ID(DE_TABBTN3),
	WINDOW_ID(DE_TABBTN4),
	WINDOW_ID(DE_TABBTN5),
	WINDOW_ID(DE_TABBTN6),

	WINDOW_ID(DE_TABBTN7),
	WINDOW_ID(DE_TABDLG1),			// 280
	WINDOW_ID(DE_TABDLG2),
	WINDOW_ID(DE_TABDLG3),
	WINDOW_ID(DE_TABDLG4), 
	WINDOW_ID(DE_TABDLG5),
	WINDOW_ID(DE_TABDLG6),
	WINDOW_ID(DE_TABDLG7),
	WINDOW_ID(DE_BUYITEM),
	WINDOW_ID(DE_SELLITEM),

	WINDOW_ID(DE_MONEYEDIT),
/*￠￥UAaA¡E*/
	WINDOW_ID(QI_QUICKDLG),			// 290
	WINDOW_ID(QI_PREVPAGEBTN),
	WINDOW_ID(QI_NEXTPAGEBTN),
	WINDOW_ID(QI_SHAPEBTN), 
	WINDOW_ID(QI_PAGESHEET1),
	WINDOW_ID(QI_PAGESHEET2),
	WINDOW_ID(QI_PAGESHEET3),
	WINDOW_ID(QI_PAGESHEET4),

/* Aⓒø￠￢?AI ¡ÆOAIAo */
	WINDOW_ID(CG_GUAGEDLG),			
	WINDOW_ID(CG_GUAGELEVEL),	

	WINDOW_ID(CG_GUAGENAME),		// 300
	WINDOW_ID(CG_GUAGELIFE),
	WINDOW_ID(CG_GUAGESHIELD),
	WINDOW_ID(CG_GUAGENAERYUK), 
	WINDOW_ID(CG_GUAGEEXPPOINT),
	WINDOW_ID(CG_GUAGEEXPPOINTTEXT),
	WINDOW_ID(CG_GUAGEMUSSANG),
	WINDOW_ID(CG_MUSSANGSTART),
	WINDOW_ID(CG_MUSSANG1),
	WINDOW_ID(CG_MUSSANG2),
	WINDOW_ID(CG_GUAGELIFETEXT),
	WINDOW_ID(CG_GUAGESHIELDTEXT),
	WINDOW_ID(CG_GUAGENAERYUKTEXT),
	// magi82 //////////////////////////////////////////////////////////////////////////
	WINDOW_ID(EXP_POINT1),
	WINDOW_ID(EXP_POINT2),
	WINDOW_ID(EXP_POINT3),
	WINDOW_ID(EXP_POINT4),
	////////////////////////////////////////////////////////////////////////////////////

	WINDOW_ID(PA_MEMBER1DLG),	

	WINDOW_ID(PA_MEMBER2DLG),
	WINDOW_ID(PA_MEMBER3DLG),
	WINDOW_ID(PA_MEMBER4DLG),
	WINDOW_ID(PA_MEMBER5DLG),
	WINDOW_ID(PA_MEMBER6DLG),
	
	WINDOW_ID(PA_MEMBER1NAME),
	WINDOW_ID(PA_MEMBER2NAME),
	WINDOW_ID(PA_MEMBER3NAME),
	WINDOW_ID(PA_MEMBER4NAME),	
	WINDOW_ID(PA_MEMBER5NAME),	
	WINDOW_ID(PA_MEMBER6NAME),

	WINDOW_ID(PA_GUAGEMEMBER1LIFE),
	WINDOW_ID(PA_GUAGEMEMBER2LIFE),
	WINDOW_ID(PA_GUAGEMEMBER3LIFE),
	WINDOW_ID(PA_GUAGEMEMBER4LIFE),
	WINDOW_ID(PA_GUAGEMEMBER5LIFE),
	WINDOW_ID(PA_GUAGEMEMBER6LIFE),

	WINDOW_ID(PA_GUAGEMEMBER1NAERYUK),
	WINDOW_ID(PA_GUAGEMEMBER2NAERYUK),
	WINDOW_ID(PA_GUAGEMEMBER3NAERYUK),	
	WINDOW_ID(PA_GUAGEMEMBER4NAERYUK),
	WINDOW_ID(PA_GUAGEMEMBER5NAERYUK),
	WINDOW_ID(PA_GUAGEMEMBER6NAERYUK),
	
	WINDOW_ID(PA_MEMBER1LEVEL),
	WINDOW_ID(PA_MEMBER2LEVEL),
	WINDOW_ID(PA_MEMBER3LEVEL),
	WINDOW_ID(PA_MEMBER4LEVEL),
	WINDOW_ID(PA_MEMBER5LEVEL),
	WINDOW_ID(PA_MEMBER6LEVEL),	
	
	WINDOW_ID(PA_BTNDLG),	
	WINDOW_ID(PA_BACKGROUND),
	WINDOW_ID(PA_SECEDEBTN),	
	WINDOW_ID(PA_TRANSFERBTN),		
	WINDOW_ID(PA_FORCEDSECEDEBTN),
	WINDOW_ID(PA_BREAKUPBTN),
	WINDOW_ID(PA_ADDPARTYMEMBERBTN),
	WINDOW_ID(PA_WARSUGGESTBTN),
	WINDOW_ID(PA_OPTIONBTN),
	WINDOW_ID(PA_MEMBERBTN),
	
	//2008. 5. 21. CBH - 방파 생성 다이얼로그 인터페이스 수정
	//WINDOW_ID(PA_CREATEDLG),
	//WINDOW_ID(PA_CREATECOMBOX),
	//WINDOW_ID(PA_CREATECOMBOXBTN),
	//WINDOW_ID(PA_CREATEOK),
	//WINDOW_ID(PA_CREATECANCEL),
	WINDOW_ID(PA_CREATEDLG),
		WINDOW_ID(PA_CREATE_THEME),
		WINDOW_ID(PA_CREATE_MINLEVEL),
		WINDOW_ID(PA_CREATE_MAXLEVEL),
		WINDOW_ID(PA_CREATE_PUBLIC),
		WINDOW_ID(PA_CREATE_PRIVATE),
		WINDOW_ID(PA_CREATE_COMBOX),
		WINDOW_ID(PA_CREATE_DIVISION),
		WINDOW_ID(PA_CREATE_DIVISIONBTN),
		WINDOW_ID(PA_CREATE_MEMBERNUM),
		WINDOW_ID(PA_CREATE_MEMBERNUMBTN),
		WINDOW_ID(PA_CREATE_OK),
		WINDOW_ID(PA_CREATE_CANCEL),

	//////////////////////////////////////////////

	WINDOW_ID(PA_INVITEDLG),
	WINDOW_ID(PA_INVITER),
	WINDOW_ID(PA_INVITEDISTRIBUTE),
	WINDOW_ID(PA_INVITEOK),
	WINDOW_ID(PA_INVITECANCEL),

	/*GUILD */
	//create
	WINDOW_ID(GD_CREATEDLG),
	WINDOW_ID(GD_CNAME),
	WINDOW_ID(GD_CINTROTEXT),
	WINDOW_ID(GD_CLOCATION),
	WINDOW_ID(GD_CCREATEOKBTN),
	WINDOW_ID(CR_CAP),	// magi82 - 문하생 관련(070122)
	//guild
	WINDOW_ID(GD_GUILDDLG),
	WINDOW_ID(GD_NAME),
	WINDOW_ID(GD_LEVEL),
	WINDOW_ID(GD_MASTER),
	WINDOW_ID(GD_MEMBERNUM),
	WINDOW_ID(GD_LOCATION),
	WINDOW_ID(GD_NAMES),
	WINDOW_ID(GD_LEVELS),
	WINDOW_ID(GD_MASTERS),
	WINDOW_ID(GD_MEMBERNUMS),
	WINDOW_ID(GD_LOCATIONS),
	WINDOW_ID(GD_UNIONNAMES),
	WINDOW_ID(GD_UNIONNAME),
	WINDOW_ID(GD_MEMBERINFOPUSHUPBTN),
	WINDOW_ID(GD_GUILFUNCPUSHUPBTN),
	WINDOW_ID(GD_RELATIONBTN),
	WINDOW_ID(GP_TIME),//Add 060803 by wonju
	WINDOW_ID(GD_MEMBERLIST),
	WINDOW_ID(GD_BANMEMBER),		//m_pGuildBtn[0]
	WINDOW_ID(GD_GIVEMEMBERNICK),
	WINDOW_ID(GD_GIVEMEMBERRANK),
	WINDOW_ID(GD_INVITEMEMBER),
	WINDOW_ID(GD_SECEDE),
	// 06. 03. 문파공지 - 이영준
	WINDOW_ID(GD_NOTICE),
	WINDOW_ID(GD_INVITEUNION),
	WINDOW_ID(GD_SECEDEUNION),
	WINDOW_ID(GD_REMOVEUNION),
	WINDOW_ID(GD_DECLARE),
	WINDOW_ID(GD_SUGGEST),
	WINDOW_ID(GD_SURRENDER),

	//Add 060803 by wonju---------------
	WINDOW_ID(GD_PLUSTIME),
	WINDOW_ID(GD_MUNHA),
	WINDOW_ID(GD_PLUSTIMESTART),
	WINDOW_ID(GD_POSITION),
	WINDOW_ID(GD_RANK),
	
	//GuildPlusTime - 항목
	WINDOW_ID(GD_POINT),
	WINDOW_ID(GD_PLUSTIMELIST),
	//------------------------------------
		
	//invite
	WINDOW_ID(GD_INVITEDlG),
	WINDOW_ID(GD_IINVITE),
	WINDOW_ID(GD_IOKBTN),
	WINDOW_ID(GD_ICANCELBTN),
	//guild mark
	WINDOW_ID(GDM_MARKREGISTDLG),
	WINDOW_ID(GDM_REGISTOKBTN),
	WINDOW_ID(GDM_NAMEEDIT),
	WINDOW_ID(GDM_INFOTEXT),
	WINDOW_ID(GUM_REGISTOKBTN),
	//guild levelup
	WINDOW_ID(GD_LEVELUPDLG),
	WINDOW_ID(GD_LU1NOTCOMPLETE),
	WINDOW_ID(GD_LU2NOTCOMPLETE),
	WINDOW_ID(GD_LU3NOTCOMPLETE),
	WINDOW_ID(GD_LU4NOTCOMPLETE),
	WINDOW_ID(GD_LU1COMPLETE),
	WINDOW_ID(GD_LU2COMPLETE),
	WINDOW_ID(GD_LU3COMPLETE),
	WINDOW_ID(GD_LU4COMPLETE),
	WINDOW_ID(GD_LUOKBTN),
	WINDOW_ID(GD_LU1),
	WINDOW_ID(GD_LU2),
	WINDOW_ID(GD_LU3),
	WINDOW_ID(GD_LU4),
	WINDOW_ID(GD_LU5),
	//guild nick name 
	WINDOW_ID(GD_NICKNAMEDLG),
	WINDOW_ID(GD_NICKTEXTAREA),
	WINDOW_ID(GD_NICKNAMEEDIT),
	WINDOW_ID(GD_NREGISTOKBTN),	
	//guild change rank
	WINDOW_ID(GDR_RANKDLG),
	WINDOW_ID(GDR_DRANKCOMBOBOX),
	WINDOW_ID(GDR_RANKCOMBOBOX),
	WINDOW_ID(GDR_DOKBTN),
	WINDOW_ID(GDR_OKBTN),
	WINDOW_ID(GDR_MEMBERNAME),	
	//guild warehouse
	WINDOW_ID(GDW_WAREHOUSEDLG),
	WINDOW_ID(GDW_WAREHOUSE1BTN),
	WINDOW_ID(GDW_WAREHOUSE2BTN),
	WINDOW_ID(GDW_TABDLG1),
	WINDOW_ID(GDW_TABDLG2),
	WINDOW_ID(GDW_PUTINMONEYBTN),
	WINDOW_ID(GDW_PUTOUTMONEYBTN),
	WINDOW_ID(GDW_MONEY),
	//guild union
	WINDOW_ID(GDU_CREATEDLG),
		WINDOW_ID(GDU_NAME),
		WINDOW_ID(GDU_TEXT),	
		WINDOW_ID(GDU_OKBTN),

	//C¡I¡¾ⓒo
	WINDOW_ID(PYO_PYOGUKDLG),
	WINDOW_ID(PYO_PYOGUKLISTBTN),
	WINDOW_ID(PYO_NOBUYBTN),
	WINDOW_ID(PYO_PYOGUKINFO1),
	WINDOW_ID(PYO_PYOGUKINFO2),
	WINDOW_ID(PYO_PYOGUKINFO3),
	WINDOW_ID(PYO_PYOGUK1BTN),
	WINDOW_ID(PYO_PYOGUK2BTN),
	WINDOW_ID(PYO_PYOGUK3BTN),
	WINDOW_ID(PYO_PYOGUK4BTN),
	WINDOW_ID(PYO_PYOGUK5BTN),
	WINDOW_ID(PYO_PYOGUKLCTRL),
	WINDOW_ID(PYO_PYOGUKHAVE),
	WINDOW_ID(PYO_PYOGUKHAVESTC),
	WINDOW_ID(PYO_BUYPYOGUKBTN),
	WINDOW_ID(PYO_MONEY),
	WINDOW_ID(PYO_MONEYIMG),
	WINDOW_ID(PYO_MONEYBACKIMG),
	WINDOW_ID(PYO_PUTINMONEYBTN),
	WINDOW_ID(PYO_PUTOUTMONEYBTN),
	WINDOW_ID(PYO_WAREITEM1),
	WINDOW_ID(PYO_WAREITEM2),
	WINDOW_ID(PYO_WAREITEM3),
	WINDOW_ID(PYO_WAREITEM4),
	WINDOW_ID(PYO_WAREITEM5),
	WINDOW_ID(PYO_NOWARE),
	WINDOW_ID(PYO_NOWARE1),
	WINDOW_ID(PYO_NOBUYPYOGUKBTN),
	WINDOW_ID(PYO_WAREIMAGE),

	//AEAo
	WINDOW_ID(NOTE_NOTEDLG),
	WINDOW_ID(NOTE_NOTELISTLCTL),
	WINDOW_ID(NOTE_NOTELISTCHK1),
	WINDOW_ID(NOTE_NOTELISTCHK2),
	WINDOW_ID(NOTE_NOTELISTCHK3),
	WINDOW_ID(NOTE_NOTELISTCHK4),
	WINDOW_ID(NOTE_NOTELISTCHK5),
	WINDOW_ID(NOTE_NOTELISTCHK6),
	WINDOW_ID(NOTE_NOTELISTCHK7),
	WINDOW_ID(NOTE_NOTELISTCHK8),
	WINDOW_ID(NOTE_NOTELISTCHK9),
	WINDOW_ID(NOTE_NOTELISTCHK10),
	WINDOW_ID(NOTE_NOTELISTCHK11),
	WINDOW_ID(NOTE_WRITENOTEBTN),
	WINDOW_ID(NOTE_DELNOTEBTN),
	WINDOW_ID(NOTE_TABBTN1),
	WINDOW_ID(NOTE_TABBTN2),
	WINDOW_ID(NOTE_PAGE1BTN),
	WINDOW_ID(NOTE_PAGE2BTN),
	WINDOW_ID(NOTE_PAGE3BTN),
	WINDOW_ID(NOTE_PAGE4BTN),
	WINDOW_ID(NOTE_PAGE5BTN),

	//A¡I¡¾￠￢
	WINDOW_ID(FRI_FRIENDDLG),
	WINDOW_ID(FRI_FRIENDLISTLCTL),
	WINDOW_ID(FRI_FRIENDLISTCHK1),
	WINDOW_ID(FRI_FRIENDLISTCHK2),
	WINDOW_ID(FRI_FRIENDLISTCHK3),
	WINDOW_ID(FRI_FRIENDLISTCHK4),
	WINDOW_ID(FRI_FRIENDLISTCHK5),
	WINDOW_ID(FRI_FRIENDLISTCHK6),
	WINDOW_ID(FRI_FRIENDLISTCHK7),
	WINDOW_ID(FRI_FRIENDLISTCHK8),
	WINDOW_ID(FRI_FRIENDLISTCHK9),
	WINDOW_ID(FRI_FRIENDLISTCHK10),
	WINDOW_ID(FRI_PAGE1BTN),
	WINDOW_ID(FRI_PAGE2BTN),
	WINDOW_ID(FRI_PAGE3BTN),
	WINDOW_ID(FRI_ADDFRIENDBTN),
	WINDOW_ID(FRI_DELFRIENDBTN),
	WINDOW_ID(FRI_SENDNOTEBTN),
	WINDOW_ID(FRI_SENDWHISPERBTN),
	
	//ⓒoI￠￥I AEAo
	WINDOW_ID(NOTE_MRTITLE),
	WINDOW_ID(NOTE_MWTITLE),
	WINDOW_ID(NOTE_MINNOTEDLG),
	WINDOW_ID(NOTE_MRECEIVEREDIT),
	WINDOW_ID(NOTE_MRNOTETEXTREA),
	WINDOW_ID(NOTE_MWNOTETEXTREA),
	WINDOW_ID(NOTE_MSENDOKBTN),
	WINDOW_ID(NOTE_MSENDCANCELBTN),
	WINDOW_ID(NOTE_MRECEIVER),
	WINDOW_ID(NOTE_MSENDER),
	WINDOW_ID(NOTE_MSENDERSTC),
	WINDOW_ID(NOTE_MREPLYBTN),
	WINDOW_ID(NOTE_MDELETEBTN),
	
	//ⓒoI￠￥ICw¡i
	WINDOW_ID(FRI_MINIFRIENDDLG),
	WINDOW_ID(FRI_NAME),
	WINDOW_ID(FRI_NAMEEDIT),
	WINDOW_ID(FRI_ADDOKBTN),
	WINDOW_ID(FRI_ADDCANCELBTN),	

	
	
//KES DIALOG
/*￠￢AA¨I¡¤I¨u¨u¨¡AA¡E*/
	WINDOW_ID(MAC_MACRODLG),			//￠￥UAI¨uo¡¤I¡¾¡¿ ¨uⓒª¨u¡ⓒ￠?I ￠￢A¨u¨¡¨uⓒ￢ CN￠￥U.
	WINDOW_ID(MAC_BTN_SAVE),
	WINDOW_ID(MAC_BTN_DEFAULT),
	WINDOW_ID(MAC_EB_QUICKITEM01),
	WINDOW_ID(MAC_EB_QUICKITEM02),
	WINDOW_ID(MAC_EB_QUICKITEM03),
	WINDOW_ID(MAC_EB_QUICKITEM04),
	WINDOW_ID(MAC_EB_QUICKITEM05),
	WINDOW_ID(MAC_EB_QUICKITEM06),
	WINDOW_ID(MAC_EB_QUICKITEM07),
	WINDOW_ID(MAC_EB_MUGONGDLG),
	WINDOW_ID(MAC_EB_INVENTORYDLG),
	WINDOW_ID(MAC_EB_CHARACTERDLG),
	WINDOW_ID(MAC_EB_MUNPADLG),
	WINDOW_ID(MAC_EB_MINIMAP),

	WINDOW_ID(MAC_EB_QUESTDLG),
	WINDOW_ID(MAC_EB_EXITDLG),
	WINDOW_ID(MAC_EB_CLOSE_ACTIVEDLG),
	WINDOW_ID(MAC_EB_MOVEMODE),
	WINDOW_ID(MAC_EB_GYUNGGONG),
	WINDOW_ID(MAC_EB_PGDN_QUICKSLOT),
	WINDOW_ID(MAC_EB_PGUP_QUICKSLOT),
	WINDOW_ID(MAC_EB_UNGIMODE),
	WINDOW_ID(MAC_EB_PEACEMODE),
	WINDOW_ID(MAC_EB_AUTOATTACK),
	WINDOW_ID(MAC_EB_CAMERAMOVE_ZOOMIN),
	WINDOW_ID(MAC_EB_CAMERAMOVE_ZOOMOUT),

	WINDOW_ID(MAC_EB_FREEVIEW),
	WINDOW_ID(MAC_EB_BACKVIEW),
	WINDOW_ID(MAC_EB_QUARTERVIEW),
	WINDOW_ID(MAC_EB_LOADVIEW),
	WINDOW_ID(MAC_EB_SAVEVIEW),
	WINDOW_ID(MAC_EB_SCREENCAPTURE),
	WINDOW_ID(MAC_EB_CAMERAMOVE_UP),
	WINDOW_ID(MAC_EB_CAMERAMOVE_DOWN),
	WINDOW_ID(MAC_EB_CAMERAMOVE_RIGHT),
	WINDOW_ID(MAC_EB_CAMERAMOVE_LEFT),

/*￠?E¨uCA¡E*/
	WINDOW_ID(OTI_TABDLG),
	WINDOW_ID(OTI_SHEET1),
	WINDOW_ID(OTI_SHEET2),
	WINDOW_ID(OTI_SHEET3),
	WINDOW_ID(OTI_SHEET4),	
	WINDOW_ID(OTI_BTN_RESET),
	WINDOW_ID(OTI_BTN_OK),
	WINDOW_ID(OTI_BTN_PREVIEW),
	WINDOW_ID(OTI_BTN_CANCEL),
	WINDOW_ID(OTI_CB_NODEAL),
	WINDOW_ID(OTI_CB_NOPARTY),
	WINDOW_ID(OTI_CB_NOFRIEND),
	WINDOW_ID(OTI_CB_NOFIGHT),
	WINDOW_ID(OTI_CB_MUNPANAME),
	WINDOW_ID(OTI_CB_PARTYNAME),
	WINDOW_ID(OTI_CB_OTHERSNAME),
	WINDOW_ID(OTI_CB_GAMETIP),
	WINDOW_ID(OTI_CB_MUNPAPR),	// magi82 - 로그인시만 문파소개창 옵션지원 070108
	WINDOW_ID(OTI_CB_MEMBERDAMAGE),
	WINDOW_ID(OTI_PB_CHATMODE),
	WINDOW_ID(OTI_PB_MACROMODE),
	WINDOW_ID(OTI_BTN_SETCHAT),
	WINDOW_ID(OTI_BTN_SETMACRO),
	WINDOW_ID(OTI_CB_NOWHISPER),
	WINDOW_ID(OTI_CB_NOCHATTING),
	WINDOW_ID(OTI_CB_NOBALLOON),
	WINDOW_ID(OTI_CB_AUTOHIDE),
	WINDOW_ID(OTI_CB_WORLDHIDE),
	WINDOW_ID(OTI_CB_MUNPAHIDE),
	WINDOW_ID(OTI_CB_ALLMUNPAHIDE),
	WINDOW_ID(OTI_CB_NOSYSTEMMSG),
	WINDOW_ID(OTI_CB_NOACQUIREMSG),
	WINDOW_ID(OTI_CB_NOITEMMSG),
	WINDOW_ID(OTI_GB_GAMMA),
	WINDOW_ID(OTI_GB_SIGHT),
	WINDOW_ID(OTI_CB_CURSOR),
	WINDOW_ID(OTI_CB_HEROSHADOW),
	WINDOW_ID(OTI_CB_MONSTERSHADOW),
	WINDOW_ID(OTI_CB_OTHERSSHADOW),
	//SW060904 Add MapAmbientCtrlOptn
	WINDOW_ID(OTI_CB_AMBIENT),

#ifndef _JAPAN_LOCAL_
	//SW050822 Add GraphicCtrlOptn
	WINDOW_ID(OTI_CB_AUTOCONTROL),
	WINDOW_ID(OTI_PB_BASICGRAPHIC),
	WINDOW_ID(OTI_PB_DOWNGRAPHIC),
	WINDOW_ID(OTI_PB_BASICEFFECT),
	WINDOW_ID(OTI_PB_ONEEFFECT),
	WINDOW_ID(OTI_CB_SNOWEFFECT), // 2005.12.29일 추가 
	WINDOW_ID(OTI_CB_AVATA),

#endif	
	WINDOW_ID(OTI_TEXT_GAMMA),
	WINDOW_ID(OTI_TEXT_SIGHT),
	WINDOW_ID(OTI_TEXT_HEROSHADOW),
	WINDOW_ID(OTI_TEXT_MONSTERSHADOW),
	WINDOW_ID(OTI_TEXT_OTHERSSHADOW),
	WINDOW_ID(OTI_TEXT_BASICGRAPHIC),
	WINDOW_ID(OTI_TEXT_DOWNGRAPHIC),
	WINDOW_ID(OTI_TEXT_BASICEFFECT),
	WINDOW_ID(OTI_TEXT_ONEEFFECT),
//	WINDOW_ID(OTI_PB_ALLOFFEFFECT),
	
	WINDOW_ID(OTI_CB_BGMSOUND),
	WINDOW_ID(OTI_CB_ENVSOUND),
	WINDOW_ID(OTI_GB_BGMSOUND),
	WINDOW_ID(OTI_GB_ENVSOUND),
	
/*~¡¤aA¡E*/
	WINDOW_ID(EXT_DIALOG),
	WINDOW_ID(EXT_BTN_EXITGAME),
	WINDOW_ID(EXT_BTN_SELECTCHAR),

/*¡¾ⓒøE?A¡E*/
	WINDOW_ID(XCI_DIALOG),	
	WINDOW_ID(XCI_BTN_CLOSE),
	WINDOW_ID(XCI_BTN_LOCK),
	WINDOW_ID(XCI_BTN_EXCHANGE),
	WINDOW_ID(XCI_BTN_EXIT),
	WINDOW_ID(XCI_BTN_INPUTMONEY),
	WINDOW_ID(XCI_EB_MYMONEY),
	WINDOW_ID(XCI_EB_OPMONEY),
	WINDOW_ID(XCI_ICD_MINE),
	WINDOW_ID(XCI_ICD_OPPOSITE),
	WINDOW_ID(XCI_INFO1),
	WINDOW_ID(XCI_INFO2),
/*Aⓒø￠￢?AI¡ioAAA¡E*/
	WINDOW_ID(CSS_DIALOG),
	WINDOW_ID(CSS_BTN_PK),
	WINDOW_ID(CSS_BTN_MOVE),
	WINDOW_ID(CSS_BTN_KYUNGGONG),
	WINDOW_ID(CSS_BTN_PEACEWAR),
	WINDOW_ID(CSS_BTN_UNGI),
/*Aⓒø￠￢?AI Ac¡iyA¡E*/
	WINDOW_ID(CR_DIALOG),
	WINDOW_ID(CR_PRESENTSPOT),
	WINDOW_ID(CR_LOGINSPOT),
	WINDOW_ID(CR_TOWNSPOT),

	WINDOW_ID(CR_S1),
	WINDOW_ID(CR_S2),
	
	WINDOW_ID(ITD_UPGRADEDLG),
	WINDOW_ID(ITD_UPGRADEGRID),
	WINDOW_ID(ITD_UPGRADE_OKBTN),
	WINDOW_ID(ITD_UPGRADE_CANCELBTN),
	
	WINDOW_ID(ITMD_MIXDLG),
	WINDOW_ID(ITMD_MIXICONTITLE),
	WINDOW_ID(ITMD_MIXICONDLG),
	WINDOW_ID(ITMD_MIXICONGRIDDLG),
	WINDOW_ID(ITMD_MIXMATERIALS),
	WINDOW_ID(ITMD_MIXOKBTN),
	WINDOW_ID(ITMD_MIXCANCELBTN),

	// magi82 - Titan(070112) ////////////////////////////////////////////////
	WINDOW_ID(TITAN_TITANPARTSMAKEDLG),
		WINDOW_ID(TITAN_TITANPARTSMAKEICONTITLE),
		WINDOW_ID(TITAN_TITANPARTSMAKEICONDLG),
		WINDOW_ID(TITAN_TITANPARTSMAKEICONGRIDDLG),
		WINDOW_ID(TITAN_TITANPARTSMAKEMATERIALS),
		WINDOW_ID(TITAN_TITANPARTSMAKEOKBTN),
		WINDOW_ID(TITAN_TITANPARTSMAKECANCELBTN),
	//////////////////////////////////////////////////////////////////////////

	// magi82 - Titan(0705031)
	WINDOW_ID(TITANPARTSCHANGE_DLG),				// 타이탄 장착창
		WINDOW_ID(TITANPARTSCHANGE_WEAREDDLG),		// 타이탄 및 부품인벤토리
		WINDOW_ID(TITANPARTSCHANGE_STARTBTN),		// 부품교체
		WINDOW_ID(TITANPARTSCHANGE_TYPE),			// 등급
		WINDOW_ID(TITANPARTSCHANGE_DEFENCE_HWA),	// 화 게이지
		WINDOW_ID(TITANPARTSCHANGE_DEFENCE_SU),		// 수 게이지
		WINDOW_ID(TITANPARTSCHANGE_DEFENCE_MOK),	// 목 게이지
		WINDOW_ID(TITANPARTSCHANGE_DEFENCE_KUM),	// 금 게이지
		WINDOW_ID(TITANPARTSCHANGE_DEFENCE_TO),		// 토 게이지
		WINDOW_ID(TITANPARTSCHANGE_CHARHWA),		// 화 수치
		WINDOW_ID(TITANPARTSCHANGE_CHARSU),			// 수 수치
		WINDOW_ID(TITANPARTSCHANGE_CHARMOK),		// 목 수치
		WINDOW_ID(TITANPARTSCHANGE_CHARKUM),		// 금 수치
		WINDOW_ID(TITANPARTSCHANGE_CHARTO),			// 토 수치
		WINDOW_ID(TITANPARTSCHANGE_CHARATTACK),		// 근거리
		WINDOW_ID(TITANPARTSCHANGE_CRITICAL),		// 외/내공 일격
		WINDOW_ID(TITANPARTSCHANGE_LONGATTACK),		// 원거리
		WINDOW_ID(TITANPARTSCHANGE_DISTANCE),		// 사정거리
		WINDOW_ID(TITANPARTSCHANGE_CHARLIFE),		// 생명력
		WINDOW_ID(TITANPARTSCHANGE_CHARDEFENSE),	// 방어력
		WINDOW_ID(TITANPARTSCHANGE_CHARNAERYUK),	// 내력
		WINDOW_ID(TITANPARTSCHANGE_HOSINDEFENSE),	// 호신강기
		WINDOW_ID(TITANPARTSCHANGE_LOOKBTN),		// 미리보기
		WINDOW_ID(TITANPARTSCHANGE_ALLREPAIR),		// 전체수리
		WINDOW_ID(TITANPARTSCHANGE_REPAIR),			// 각개수리
	//////////////////////////////////////////////////////////////////////////

	//2007. 9. 11. CBH - 타이탄 수리 다이얼로그
	WINDOW_ID(TITAN_REPAIR_DLG),				// 타이탄 수리창
		WINDOW_ID(TITAN_REPAIR_ALL),		// 전체 수리
		WINDOW_ID(TITAN_REPAIR_PART),		// 개별 수리
	//////////////////////////////////////////////////////////////////////////

	// magi82 - Titan(070125) ////////////////////////////////////////////////
	WINDOW_ID(TITANMIX_DLG),
		WINDOW_ID(TITANMIX_MIXICONDLG),
		WINDOW_ID(TITANMIX_GB_GAMMA),		// 타이탄 크기 게이지
		WINDOW_ID(TITANMIX_CHARTYPE),		// 종류
		WINDOW_ID(TITANMIX_DEFENCE_HWA),	// 화저항력게이지
		WINDOW_ID(TITANMIX_DEFENCE_SU),		// 수저항력게이지
		WINDOW_ID(TITANMIX_DEFENCE_MOK),	// 목저항력게이지
		WINDOW_ID(TITANMIX_DEFENCE_KUM),	// 금저항력게이지
		WINDOW_ID(TITANMIX_DEFENCE_TO),		// 토저항력게이지
		WINDOW_ID(TITANMIX_CHARHWA),		// 화저항수치
		WINDOW_ID(TITANMIX_CHARSU),			// 수저항수치
		WINDOW_ID(TITANMIX_CHARMOK),		// 목저항수치
		WINDOW_ID(TITANMIX_CHARKUM),		// 금저항수치
		WINDOW_ID(TITANMIX_CHARTO),			// 토저항수치
		WINDOW_ID(TITANMIX_CHARATTACK),		// 근거리
		WINDOW_ID(TITANMIX_CRITICAL),		// 외/내공일격
		WINDOW_ID(TITANMIX_LONGATTACK),		// 장거리공격
		WINDOW_ID(TITANMIX_DISTANCE),		// 사정거리
		WINDOW_ID(TITANMIX_CHARLIFE),		// 생명력
		WINDOW_ID(TITANMIX_CHARDEFENSE),	// 방어력
		//WINDOW_ID(TITANMIX_CHARNAERYUK),	// 내력
		WINDOW_ID(TITANMIX_MAGICATTACK),	// 마공
		WINDOW_ID(TITANMIX_LOOKBTN),		// 미리보기
		WINDOW_ID(TITANMIX_STARTBTN),		// 제조시작
	//////////////////////////////////////////////////////////////////////////

	// magi82 - Titan(070131)
	WINDOW_ID(TITANUPGRADE_DLG),
		WINDOW_ID(TITANUPGRADE_TITANICONDLG),
		WINDOW_ID(TITANUPGRADE_NAME_STATIC),
		WINDOW_ID(TITANUPGRADE_ICONGRIDDLG),
		WINDOW_ID(TITANUPGRADE_RFEE),
		WINDOW_ID(TITANUPGRADE_BTN_OK),
	//////////////////////////////////////////////////////////////////////////

	// magi82 - Titan(070202)
	WINDOW_ID(TITANBREAK_DLG),
		WINDOW_ID(TITANBREAK_TITANICONDLG),
		WINDOW_ID(TITANBREAK_BREAKICONGRIDDLG),
		WINDOW_ID(TITANBREAK_RFEE),
		WINDOW_ID(TITANBREAK_BTN_OK),
		WINDOW_ID(TITANBREAK_BTN_CANCEL),
	//////////////////////////////////////////////////////////////////////////

	WINDOW_ID(TITANPARTSCHANGEPREVIEW_DLG),	// magi82 - Titan(070212)

	// magi82 - Titan(070222)
	WINDOW_ID(TITAN_INVENTORY_DLG),					// 타이탄인벤창
		WINDOW_ID(TITAN_INVENTORY_WEAREDDLG),		// 타이탄 및 부품인벤토리
		WINDOW_ID(TITAN_INVENTORY_VIEW_DLG),		// 타이탄 장착뷰
		WINDOW_ID(TITAN_INVENTORY_INVEN_SET_DLG),	// 타이탄 캐쉬아이템
		WINDOW_ID(TITAN_INVENTORY_TYPE),			// 등급
		WINDOW_ID(TITAN_INVENTORY_DEFENCE_HWA),		// 화게이지
		WINDOW_ID(TITAN_INVENTORY_DEFENCE_SU),		// 수게이지
		WINDOW_ID(TITAN_INVENTORY_DEFENCE_MOK),		// 목게이지
		WINDOW_ID(TITAN_INVENTORY_DEFENCE_KUM),		// 금게이지
		WINDOW_ID(TITAN_INVENTORY_DEFENCE_TO),		// 토게이지
		WINDOW_ID(TITAN_INVENTORY_CHARHWA),			// 화수치
		WINDOW_ID(TITAN_INVENTORY_CHARSU),			// 수수치
		WINDOW_ID(TITAN_INVENTORY_CHARMOK),			// 목수치
		WINDOW_ID(TITAN_INVENTORY_CHARKUM),			// 금수치
		WINDOW_ID(TITAN_INVENTORY_CHARTO),			// 토수치
		WINDOW_ID(TITAN_INVENTORY_CHARATTACK),		// 근거리
		WINDOW_ID(TITAN_INVENTORY_LONGATTACK),		// 원거리
		WINDOW_ID(TITAN_INVENTORY_MAGICATTACK),		// 마력공격
		WINDOW_ID(TITAN_INVENTORY_CRITICAL),		// 일격
		WINDOW_ID(TITAN_INVENTORY_DISTANCE),		// 사정거리
		WINDOW_ID(TITAN_INVENTORY_CHARDEFENSE),		// 방어력
		WINDOW_ID(TITAN_INVENTORY_CHARLIFE),		// 연료
		//WINDOW_ID(TITAN_INVENTORY_CHARNAERYUK),		// 마력
	//////////////////////////////////////////////////////////////////////////

	// magi82 - Titan(070305)
	WINDOW_ID(TITAN_GUAGE_DLG),						// 타이탄게이지창
		WINDOW_ID(TITAN_GUAGE_CHARLIFE),
		WINDOW_ID(TITAN_GUAGE_CHARNAERYUK),
		WINDOW_ID(TITAN_GUAGE_LOOKBTN),
		WINDOW_ID(TITAN_GUAGE_HPTEXT),
		WINDOW_ID(TITAN_GUAGE_MPTEXT),

	WINDOW_ID(TITAN_MUGONGMIX_Dlg),					// 타이탄 무공합성창
		WINDOW_ID(TITAN_MUGONGMIX_SLOT_MUGONG_DLG),
		WINDOW_ID(TITAN_MUGONGMIX_SLOT_MUNSEO_DLG),
		WINDOW_ID(TITAN_MUGONGMIX_OKBTN),
		WINDOW_ID(TITAN_MUGONGMIX_CANCELBTN),
	//////////////////////////////////////////////////////////////////////////

	// magi82 - Titan(070320)
	WINDOW_ID(TITAN_USE_DLG),
		WINDOW_ID(TITAN_USE_SLOT),
		WINDOW_ID(TITAN_USE_OKBTN),
		WINDOW_ID(TITAN_USE_CANCELBTN),
	//////////////////////////////////////////////////////////////////////////

	// magi82 - Titan(070321)
	WINDOW_ID(TITAN_BONGIN_DLG),
		WINDOW_ID(TITAN_BONGIN_SLOT),
		WINDOW_ID(TITAN_BONGIN_OKBTN),
		WINDOW_ID(TITAN_BONGIN_CANCELBTN),
	//////////////////////////////////////////////////////////////////////////

	// 2007. 9. 13. CBH - 타이탄 소환 게이지
	WINDOW_ID(TITAN_RECALL_DLG),
		WINDOW_ID(TITAN_RECALL_GUAGE),
		WINDOW_ID(TITAN_RECALL_TIME),
		WINDOW_ID(TITAN_RECALL_CANCEL),		
	//////////////////////////////////////////////////////////////////////////

	// magi82 - UniqueItem(070703)
	WINDOW_ID(UNIQUEITEMCURSECANCELLATION_DLG),
		WINDOW_ID(UNIQUEITEMCURSECANCELLATION_ICON),
		WINDOW_ID(UNIQUEITEMCURSECANCELLATION_OKBTN),
		WINDOW_ID(UNIQUEITEMCURSECANCELLATION_CANCELBTN),
	//////////////////////////////////////////////////////////////////////////

	// magi82 - UniqueItem(070709)
	WINDOW_ID(UNIQUEITEMMIX_DLG),
		WINDOW_ID(UNIQUEITEMMIX_MATERIALS),
		WINDOW_ID(UNIQUEITEMMIX_ICON),
		WINDOW_ID(UNIQUEITEMMIX_OKBTN),
		WINDOW_ID(UNIQUEITEMMIX_CANCELBTN),
	//////////////////////////////////////////////////////////////////////////

	// magi82 - SOS(070724)
	WINDOW_ID(SOS_SOSDLG),
		WINDOW_ID(SOS_MEMBERLIST),
		WINDOW_ID(SOS_OKBTN),

	// magi82 - Intro(070802)
	// 인트로 동영상 리플레이
	WINDOW_ID(INTRO_DLG),
		WINDOW_ID(INTRO_BTN_REPLAY),

	///////// 2007. 10. 22. CBH - 유니크 아이탬 조합 게이지 다이얼로그
	WINDOW_ID(UNIQUEITEMMIX_PROGRESSBAR_DLG),
		WINDOW_ID(UNIQUEITEMMIX_PROGRESS_GAGE),
		WINDOW_ID(UNIQUEITEMMIX_PROGRESSBAR_TIME),
		WINDOW_ID(UNIQUEITEMMIX_PROGRESSBAR_CANCEL),	
	/////////////////////////////////////////////////////////////////////////////////////////////////////

	///////// 2007. 10. 22. CBH - 타이탄 조합 게이지 다이얼로그
	WINDOW_ID(TITANMIX_PROGRESSBAR_DLG),
		WINDOW_ID(TITANMIX_PROGRESSBAR_GAGE),
		WINDOW_ID(TITANMIX_PROGRESSBAR_TIME),
		WINDOW_ID(TITANMIX_PROGRESSBAR_CANCEL),	
	/////////////////////////////////////////////////////////////////////////////////////////////////////

	///////// 2007. 10. 23. CBH - 타이탄 파츠 조합 게이지 다이얼로그
	WINDOW_ID(TITANPARTS_PROGRESSBAR_DLG),
		WINDOW_ID(TITANPARTS_PROGRESSBAR_GAGE),
		WINDOW_ID(TITANPARTS_PROGRESSBAR_TIME),
		WINDOW_ID(TITANPARTS_PROGRESSBAR_CANCEL),	
	/////////////////////////////////////////////////////////////////////////////////////////////////////

	//2007. 12. 4. CBH - 스킨 선택 다이얼로그
	WINDOW_ID(SKIN_SELECT_DLG),				// 스킨 선택 창
		WINDOW_ID(SKIN_SELECT_ITEMVIEW),				// 선택한 아이탬 뷰 아이콘		
		WINDOW_ID(SKIN_SELECTLIST),			// 품목 리스트
		WINDOW_ID(SKIN_SELECT_OK),			// 확인 버튼
		WINDOW_ID(SKIN_SELECT_CANCEL),		// 취소 버튼
		WINDOW_ID(SKIN_SELECT_RECOVERY),	// 되돌리기 버튼
	//////////////////////////////////////////////////////////////////////////

	//2008. 1. 16. CBH -코스튬 스킨 선택 다이얼로그
	WINDOW_ID(COSTUME_SKIN_SELECT_DLG),				// 스킨 선택 창
		WINDOW_ID(COSTUME_SKIN_SELECT_ITEMVIEW),	// 선택한 아이탬 뷰 아이콘		
		WINDOW_ID(COSTUME_SKIN_SELECTLIST),			// 품목 리스트
		WINDOW_ID(COSTUME_SKIN_SELECT_OK),			// 확인 버튼
		WINDOW_ID(COSTUME_SKIN_SELECT_CANCEL),		// 취소 버튼
		WINDOW_ID(COSTUME_SKIN_SELECT_RECOVERY),	// 되돌리기 버튼
		WINDOW_ID(COSTUME_TABBTN_HAT),				//모자 탭 버튼
		WINDOW_ID(COSTUME_TABBTN_DRESS),			//옷 탭 버튼
		WINDOW_ID(COSTUME_TABBTN_ACCESSORY),		//악세사리 탭 버튼
	//////////////////////////////////////////////////////////////////////////

	//2008. 3. 17. CBH - 보안번호 다이얼로그
	WINDOW_ID(NUMBERPAD_DLG),				// 보안번호 다이얼로그
	WINDOW_ID(NUMBERPAD_0),
	WINDOW_ID(NUMBERPAD_1),
	WINDOW_ID(NUMBERPAD_2),
	WINDOW_ID(NUMBERPAD_3),
	WINDOW_ID(NUMBERPAD_4),
	WINDOW_ID(NUMBERPAD_5),
	WINDOW_ID(NUMBERPAD_6),
	WINDOW_ID(NUMBERPAD_7),
	WINDOW_ID(NUMBERPAD_8),
	WINDOW_ID(NUMBERPAD_9),
	WINDOW_ID(NUMBERPAD_BACKSPACE),	
	//////////////////////////////////////////////////////////////////////////

	WINDOW_ID(ITR_REINFORCETITLE),
	WINDOW_ID(ITR_REINFORCEDLG),
	WINDOW_ID(ITR_REINFORCEICONDLG),
	WINDOW_ID(ITR_REINFORCEICONGRIDDLG),
	// 06. 02. 강화 재료 안내 인터페이스 추가 - 이영준
	WINDOW_ID(ITR_RFGUIDEBTN),
	WINDOW_ID(ITR_REINFORCEOKBTN),
	WINDOW_ID(ITR_REINFORCECANCELBTN),
	WINDOW_ID(ITR_REINFORCEGRAVITY),
	
	WINDOW_ID(DIS_DISSOLVEDLG),
	WINDOW_ID(DIS_DISSOLVEICONDLG),
	WINDOW_ID(DIS_DISSOLVEICONGRIDDLG),
	WINDOW_ID(DIS_DISSOLVEOKBTN),
	WINDOW_ID(DIS_DISSOLVECANCELBTN),
	WINDOW_ID(DIS_DISSOLVECOST),
	
/////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////
	//2008. 5. 23. CBH - 방파장의 방파 신청 수락 다이얼로그
	WINDOW_ID(MBI_PARTYDECISION),

	//2008. 5. 29. CBH - 방파매칭 리스트 다이얼로그
	WINDOW_ID(PARTY_MATCHING_DLG),
		WINDOW_ID(PARTYMATCHING_LEVEL_EDIT),
		WINDOW_ID(PARTYMATCHING_LIST),
		WINDOW_ID(PARTYMATCHING_RANDOMIN_BTN),
		WINDOW_ID(PARTYMATCHING_REFLESH_BTN),
		WINDOW_ID(PARTYMATCHING_JOIN_BTN),
////////////////////////////////////////////////////////////////////////////////////

/* ⓒoI￠￥I￠￢E */
	WINDOW_ID(MNM_DIALOG),
	WINDOW_ID(MNM_PARTYDISPLAY_ONOFF),
	WINDOW_ID(MNM_TOGGLEFULL),
	WINDOW_ID(MNM_MAPNAME),
	WINDOW_ID(MNM_POSXY),
/*BigMapDlg*/
	WINDOW_ID(BM_DIALOG),
	
/* ￠￢￠O￠?i¨o¨￢ */
	WINDOW_ID(INT_MOUSEBASIC),
	WINDOW_ID(INT_MOUSECLICK),

	//￠￢o¨o¨￢AI ¡ÆOAIAo A¡E
	WINDOW_ID(CG_MONSTERGUAGEDLG),
	WINDOW_ID(CG_MONSTERGUAGENAME),
	WINDOW_ID(CG_MONSTERGUAGELIFETEXT),
	WINDOW_ID(CG_MONSTERGUAGELIFE),
	WINDOW_ID(CG_MONSTERGUAGESHIELD),
	WINDOW_ID(CG_GUILDNAME),
	WINDOW_ID(CG_GUILDUNION_NAME),
	WINDOW_ID(CG_GUILDUNION_BASE),
	WINDOW_ID(CG_GUILDUNION_BTN),
	WINDOW_ID(CG_UNIONNAME),
	// 06. 01. 타겟팅창 인터페이스 변경 - 이영준
	WINDOW_ID(CG_NPCNAME),
	WINDOW_ID(CG_MONSTERGUAGELIFEBASE),

/*MenuSlotDialog*/
	WINDOW_ID(MSI_DLG),
	WINDOW_ID(MSI_PREVPAGEBTN),
	WINDOW_ID(MSI_NEXTPAGEBTN),
	WINDOW_ID(MSI_PAGESHEET1),
	WINDOW_ID(MSI_PAGESHEET2),
	WINDOW_ID(MSI_PAGESHEET3),
	WINDOW_ID(MSI_PAGESHEET4),

/*EventNotifyDialog*/
	WINDOW_ID(GMOT_OPENTALKDLG),
	WINDOW_ID(GMOT_STC_TITLE),
	WINDOW_ID(GMOT_TA_CONTEXT),

/*MallNoticeDialog*/
	WINDOW_ID(ITEM_MALLDLG),
	WINDOW_ID(ITEM_TABBTN1),
	WINDOW_ID(ITEM_TABBTN2),
	WINDOW_ID(ITEM_SHEET1),
	WINDOW_ID(ITEM_SHEET2),
	WINDOW_ID(ITEM_MALLBTN),

//////////////
//---Murim Net
//---playroom
	WINDOW_ID(MNPRI_DIALOG),
	WINDOW_ID(MNPRI_LSTDLG_TEAMA),
	WINDOW_ID(MNPRI_LSTDLG_TEAMB),
	WINDOW_ID(MNPRI_LSTDLG_OB),
	WINDOW_ID(MNPRI_BTN_TEAMA),
	WINDOW_ID(MNPRI_BTN_TEAMB),
	WINDOW_ID(MNPRI_BTN_OB),
	WINDOW_ID(MNPRI_STC_TEAMACOUNT),
	WINDOW_ID(MNPRI_STC_OBCOUNT),
	WINDOW_ID(MNPRI_STC_TEAMBCOUNT),
	WINDOW_ID(MNPRI_BTN_MOVETOA),
	WINDOW_ID(MNPRI_BTN_MOVETOOB),
	WINDOW_ID(MNPRI_BTN_MOVETOB),
	WINDOW_ID(MNPRI_LSTDLG_CHAT),
	WINDOW_ID(MNPRI_EB_CHAT),
	WINDOW_ID(MNPRI_PB_CHATTOWHOLE),
	WINDOW_ID(MNPRI_PB_CHATTOTEAM),
	WINDOW_ID(MNPRI_PB_WHISPER),
	WINDOW_ID(MNPRI_STC_TITLE),
	WINDOW_ID(MNPRI_STC_GAMEKIND),
	WINDOW_ID(MNPRI_STC_MAXPLAYER),
	WINDOW_ID(MNPRI_STC_ROOMKIND),
	WINDOW_ID(MNPRI_STC_REPAY),
	WINDOW_ID(MNPRI_BTN_INVITE),
	WINDOW_ID(MNPRI_BTN_BAN),
	WINDOW_ID(MNPRI_BTN_START),
	WINDOW_ID(MNPRI_BTN_EXIT),
//--- murimnet channel	
	WINDOW_ID(MNCNL_DIALOG),
	WINDOW_ID(MNCNL_LSTDLG_IDLIST),
	WINDOW_ID(MNCNL_LSTDLG_PLAYROOMLIST),
	WINDOW_ID(MNCNL_LSTDLG_CHANNELLIST),
	WINDOW_ID(MNCNL_LSTDLG_CHAT),
	WINDOW_ID(MNCNL_EB_CHAT),
	WINDOW_ID(MNCNL_PB_CHATTOWHOLE),
	WINDOW_ID(MNCNL_PB_CHATTOTEAM),
	WINDOW_ID(MNCNL_PB_WHISPER),
	WINDOW_ID(MNCNL_STC_TITLE),
	WINDOW_ID(MNCNL_STC_GAMEKIND),
	WINDOW_ID(MNCNL_STC_MAPNAME),
	WINDOW_ID(MNCNL_STC_MAXPLAYER),
	WINDOW_ID(MNCNL_STC_ROOMKIND),
	WINDOW_ID(MNCNL_STC_REPAY),
	WINDOW_ID(MNCNL_STC_CAPTAIN),
	WINDOW_ID(MNCNL_BTN_EXIT),
	WINDOW_ID(MNCNL_BTN_CREATE),
	WINDOW_ID(MNCNL_BTN_JOIN),
	WINDOW_ID(MNCNL_BTN_IDLIST),		//	id->channel->playroom ¨uⓒª¨u¡ⓒ￠￢| AoA¡Æ¨oA￠?A.
	WINDOW_ID(MNCNL_BTN_CHANNELLIST),	//
	WINDOW_ID(MNCNL_BTN_PLAYROOMLIST),	//
	
//---Murim Net End
//////////////////

/* A￠´ⓒøI */
	WINDOW_ID(CHA_CHANNELDLG),
	WINDOW_ID(CHA_CHANNELLIST),
	WINDOW_ID(CHA_CONNNECTOK),
	WINDOW_ID(CHA_CONNNECTCANCEL),

// ServerList
	WINDOW_ID(SL_SERVERLISTDLG),
	WINDOW_ID(SL_LISTCTRL),
	WINDOW_ID(SL_BTN_CONNECT),
	WINDOW_ID(SL_BTN_EXIT),	
	WINDOW_ID(SL_BTN_REPLAY),	

/* Co¡io¡¾Y NPC */
	WINDOW_ID(WANTNPC_DLG),
	WINDOW_ID(WANTNPC_WANTLCTRL),
	WINDOW_ID(WANTNPC_BUYPRICE),	
	WINDOW_ID(WANTNPC_MYWANTBTN),
	WINDOW_ID(WANTNPC_MYWANTSEARCHBTN),
	WINDOW_ID(WANTNPC_SORTBTN),
	WINDOW_ID(WANTNPC_LISTORDERCOMBOBOX),
	WINDOW_ID(WANTNPC_PMLISTORDERCOMBOBOX),
	WINDOW_ID(WANTNPC_BUYNPCBTN),
	WINDOW_ID(WANTNPC_BUYSEARCHBTN),
	WINDOW_ID(WANTNPC_SEARCHMODEBTN),
	WINDOW_ID(WANTNPC_SEARCHBTN),
	WINDOW_ID(WANTNPC_SEARCHEDIT),
	WINDOW_ID(WANTNPC_GIVEUPBTN),
	WINDOW_ID(WANTNPC_MYSTC),
	WINDOW_ID(WANTNPC_FRONTLISTBTN),
	WINDOW_ID(WANTNPC_1LISTBTN),
	WINDOW_ID(WANTNPC_2LISTBTN),
	WINDOW_ID(WANTNPC_3LISTBTN),
	WINDOW_ID(WANTNPC_4LISTBTN),
	WINDOW_ID(WANTNPC_5LISTBTN),
	WINDOW_ID(WANTNPC_BACKLISTBTN),
	WINDOW_ID(WANTNPC_MYFRONTLISTBTN),
	WINDOW_ID(WANTNPC_MY1LISTBTN),
	WINDOW_ID(WANTNPC_MY2LISTBTN),
	WINDOW_ID(WANTNPC_MY3LISTBTN),
	WINDOW_ID(WANTNPC_MY4LISTBTN),
	WINDOW_ID(WANTNPC_MY5LISTBTN),
	WINDOW_ID(WANTNPC_MYBACKLISTBTN),
	WINDOW_ID(WANTNPC_SEARCHFRONTLISTBTN),
	WINDOW_ID(WANTNPC_SEARCH1LISTBTN),
	WINDOW_ID(WANTNPC_SEARCH2LISTBTN),
	WINDOW_ID(WANTNPC_SEARCH3LISTBTN),
	WINDOW_ID(WANTNPC_SEARCH4LISTBTN),
	WINDOW_ID(WANTNPC_SEARCH5LISTBTN),
	WINDOW_ID(WANTNPC_SEARCHBACKLISTBTN),
	
	/* Co¡io¡¾Y ￥ii¡¤I */
	WINDOW_ID(WANTREG_DLG),
	WINDOW_ID(WANTREG_WANTEDNAME),
	WINDOW_ID(WANTREG_PRIZEEDIT),
	WINDOW_ID(WANTREG_OK),
	WINDOW_ID(WANTREG_CANCEL),
	
	/* Au¨o¨￢¨¡￠c */
	WINDOW_ID(QUE_TOTALDLG),
		WINDOW_ID(QUE_QUESTBTN),
		WINDOW_ID(QUE_WANTEDBTN),
		WINDOW_ID(QUE_JOURNALBTN),

		WINDOW_ID(QUE_QUESTDLG),
			WINDOW_ID(QUE_PAGE1BTN),
			WINDOW_ID(QUE_PAGE2BTN),
			WINDOW_ID(QUE_PAGE3BTN),
			WINDOW_ID(QUE_PAGE4BTN),
			WINDOW_ID(QUE_PAGE5BTN),
			WINDOW_ID(QUE_ITEM_GRID),
			WINDOW_ID(QUE_QUESTLIST),
			WINDOW_ID(QUE_TITLEBTN),

		WINDOW_ID(QUE_WANTEDDLG),
			WINDOW_ID(QUE_WANTEDLDLG),

		WINDOW_ID(QUE_JOURNALDLG),
			WINDOW_ID(QUE_JOURNALLISTDLG),
			WINDOW_ID(QUE_JOURNALTEXTAREA),
			WINDOW_ID(QUE_JOURNALFRONTBTN),
			WINDOW_ID(QUE_JOURNALBACKBTN),
			WINDOW_ID(QUE_JOURNALPAGE1BTN),
			WINDOW_ID(QUE_JOURNALPAGE2BTN),
			WINDOW_ID(QUE_JOURNALPAGE3BTN),
			WINDOW_ID(QUE_JOURNALPAGE4BTN),
			WINDOW_ID(QUE_JOURNALPAGE5BTN),
			WINDOW_ID(QUE_JOURNALCHECKBOX1BTN),
			WINDOW_ID(QUE_JOURNALCHECKBOX2BTN),
			WINDOW_ID(QUE_JOURNALCHECKBOX3BTN),
			WINDOW_ID(QUE_JOURNALCHECKBOX4BTN),
			WINDOW_ID(QUE_JOURNALCHECKBOX5BTN),			
			WINDOW_ID(QUE_JOURNALSAVE),
			WINDOW_ID(QUE_JOURNALSAVEDLIST),

	/*수련장*/
	//등록
	WINDOW_ID(MP_REGISTDLG),
	WINDOW_ID(MP_RMUGONGICON),
	WINDOW_ID(MP_RMUGONGINFO),
	WINDOW_ID(MP_RPRACTICEINFO),
	WINDOW_ID(MP_RFEE),
	WINDOW_ID(MP_ROKBTN),
	WINDOW_ID(MP_RCANCELBTN),
	//미션
	WINDOW_ID(MP_MISSIONDLG),
	WINDOW_ID(MP_MMISSION),
	WINDOW_ID(MP_MCAUTION),
	//회복 설명
	WINDOW_ID(MP_NOTICEDLG),
	WINDOW_ID(MP_NCAUTION),
	WINDOW_ID(MP_NREDCAUTION),
	//게이지바
	WINDOW_ID(MP_GUAGEDLG),
	WINDOW_ID(MP_GEXPGUAGE),
	WINDOW_ID(MP_GTIME),
	WINDOW_ID(MP_GEXPERCENT),
	WINDOW_ID(MP_TITLE),




////////////	
// PKLOOTING
	WINDOW_ID(PLI_IGD_ITEM),
	WINDOW_ID(PLI_STC_BADFAME),
	WINDOW_ID(PLI_STC_TIME),
	WINDOW_ID(PLI_STC_CHANCE),
	WINDOW_ID(PLI_STC_TARGETNAME),
	WINDOW_ID(PLI_STC_ITEM),
	WINDOW_ID(PLI_BTN_CLOSE),
	WINDOW_ID(PLI_STC_END),
	WINDOW_ID(PLI_STC_NONE),
	
//////////////
// BAIL
	WINDOW_ID(BAIL_DLG),
	WINDOW_ID(BAIL_TEXTAREA),
	WINDOW_ID(BAIL_OK),
	WINDOW_ID(BAIL_CANCEL),
	WINDOW_ID(BAIL_BAILEDITBOX),	

////////////////
// CHINA ADVICE
	WINDOW_ID(CNA_CNADVICEDLG),
	WINDOW_ID(CNA_TEXTAREA),
	WINDOW_ID(CNA_BTN_OK),
	
///////////////////
// ITEM DISSOLUTION
	WINDOW_ID(DIS_DISSOLUTIONDLG),
	WINDOW_ID(DIS_BASEICONDLG),
	WINDOW_ID(DIS_NUMBTN1),
	WINDOW_ID(DIS_NUMBTN2),
	WINDOW_ID(DIS_NUMBTN3),
	WINDOW_ID(DIS_ICONGRIDDLG1),
	WINDOW_ID(DIS_ICONGRIDDLG2),
	WINDOW_ID(DIS_ICONGRIDDLG3),
	WINDOW_ID(DIS_OKBTN),
	WINDOW_ID(DIS_CANCELBTN),
	
////////////////////
// SHOPITEM
	WINDOW_ID(ITMALL_BASEDLG),
		WINDOW_ID(ITMALL_GRID1),
		WINDOW_ID(ITMALL_GRID2),
		WINDOW_ID(ITMALL_GRID3),
		WINDOW_ID(ITMALL_BTN1),
		WINDOW_ID(ITMALL_BTN2),
		WINDOW_ID(ITMALL_BTN3),

////////////////////
// MOVEDIALOG
	WINDOW_ID(SA_MOVEDLG),
		WINDOW_ID(SA_MOVELIST),
		WINDOW_ID(SA_CHANGNAME),
		WINDOW_ID(SA_MOVEOK),
		WINDOW_ID(SA_MOVEDEL),
		WINDOW_ID(SA_MOVETABBTN1),
		WINDOW_ID(SA_MOVETABBTN2),		

////////////////////
// SAVEPOINTDIALOG
	WINDOW_ID(CHA_NAMEDLG),
		WINDOW_ID(CHA_NAMEEDITBOX),
		WINDOW_ID(CHA_NAME_OKBTN),
		WINDOW_ID(CHA_NAME_CANCELBTN),

//------- guildfieldwar
	WINDOW_ID(GFW_DECLAREDLG),
		WINDOW_ID(GFW_DECLARE_MSG),
		WINDOW_ID(GFW_DECLARE_EDITBOX),
		WINDOW_ID(GFW_MONEY_EDITBOX),
		WINDOW_ID(GFW_MONEY_MSG1),
		WINDOW_ID(GFW_MONEY_MSG2),
		WINDOW_ID(GFW_MONEY_MSG3),
		WINDOW_ID(GFW_MONEY_CHK),
		WINDOW_ID(GFW_MONEY_STATIC),
		WINDOW_ID(GFW_DECLARE_OKBTN),
		WINDOW_ID(GFW_DECLARE_CANCELBTN),
	WINDOW_ID(GFW_RESULTDLG),
		WINDOW_ID(GFW_RESULT_TITILE),
		WINDOW_ID(GFW_RESULT_MSG),
		WINDOW_ID(GFW_RESULT_0),
		WINDOW_ID(GFW_RESULT_1),
		WINDOW_ID(GFW_RESULT_2),
		WINDOW_ID(GFW_RESULT_3),
		WINDOW_ID(GFW_RESULT_4),
		WINDOW_ID(GFW_RESULT_5),
		WINDOW_ID(GFW_RESULT_OKBTN),
		WINDOW_ID(GFW_RESULT_CANCELBTN),
		WINDOW_ID(GFW_RESULT_CONFIRMBTN),
	WINDOW_ID(GFW_INFODLG),
		WINDOW_ID(GFW_INFO_TITLE),
		WINDOW_ID(GFW_INFO_MSG),
		WINDOW_ID(GFW_INFO_LIST),
		WINDOW_ID(GFW_INFO_TEXT),
		WINDOW_ID(GFW_INFO_STATIC_0),
		WINDOW_ID(GFW_INFO_STATIC_1),
		WINDOW_ID(GFW_INFO_STATIC_2),
		WINDOW_ID(GFW_INFO_SUGGEST_OKBTN),
		WINDOW_ID(GFW_INFO_SURREND_OKBTN),
		WINDOW_ID(GFW_GDU_REMOVE_OKBTN),
		WINDOW_ID(GFW_INFO_CANCELBTN),
	WINDOW_ID(GW_INFODLG),
		WINDOW_ID(GW_BLACKLIST),
		WINDOW_ID(GW_WHITELIST),
		WINDOW_ID(GW_INFOSTATIC),
		WINDOW_ID(GW_INFOCLOSEBTN),
	
///////////////////
// SkillPointRedistibute
	WINDOW_ID(SK_POINTDLG),
		WINDOW_ID(SK_POINTAGAIN1BTN),
		WINDOW_ID(SK_POINTAGAIN2BTN),
		WINDOW_ID(SK_POINTAGAIN3BTN),
		WINDOW_ID(SK_ICONGRID1),
		WINDOW_ID(SK_ICONGRID2),
		WINDOW_ID(SK_ICONGRID3),
		WINDOW_ID(SK_POINTSTATIC),
		WINDOW_ID(SK_USESTATIC),
		WINDOW_ID(SK_ORIGINALSTATIC),
		WINDOW_ID(SK_UPBTN),
		WINDOW_ID(SK_DOWNBTN),
		WINDOW_ID(SK_OKBTN),

////////////////////
// SkillPointNotify
	WINDOW_ID(SK_POINTNOTIFYDLG),
		WINDOW_ID(SK_INFOTEXT1),
		WINDOW_ID(SK_INFOTEXT2),
		WINDOW_ID(SK_STARTBTN),

// partywar
	WINDOW_ID(PW_DLG),
		WINDOW_ID(PW_BTN_LOCK),
		WINDOW_ID(PW_BTN_UNLOCK),
		WINDOW_ID(PW_BTN_START),
		WINDOW_ID(PW_BTN_CANCEL),
		WINDOW_ID(PW_TITLE),
		WINDOW_ID(PW_TEAM1),
		WINDOW_ID(PW_TEAM2),
		WINDOW_ID(PW_TIME),
		WINDOW_ID(PW_CB_MEMBER0),
		WINDOW_ID(PW_CB_MEMBER1),
		WINDOW_ID(PW_CB_MEMBER2),
		WINDOW_ID(PW_CB_MEMBER3),
		WINDOW_ID(PW_CB_MEMBER4),
		WINDOW_ID(PW_CB_MEMBER5),
		WINDOW_ID(PW_CB_MEMBER6),
		WINDOW_ID(PW_CB_MEMBER7),
		WINDOW_ID(PW_CB_MEMBER8),
		WINDOW_ID(PW_CB_MEMBER9),
		WINDOW_ID(PW_CB_MEMBER10),
		WINDOW_ID(PW_CB_MEMBER11),
		WINDOW_ID(PW_CB_MEMBER12),
		WINDOW_ID(PW_CB_MEMBER13),
		WINDOW_ID(PW_MEMBER0),
		WINDOW_ID(PW_MEMBER1),
		WINDOW_ID(PW_MEMBER2),
		WINDOW_ID(PW_MEMBER3),
		WINDOW_ID(PW_MEMBER4),
		WINDOW_ID(PW_MEMBER5),
		WINDOW_ID(PW_MEMBER6),
		WINDOW_ID(PW_MEMBER7),
		WINDOW_ID(PW_MEMBER8),
		WINDOW_ID(PW_MEMBER9),
		WINDOW_ID(PW_MEMBER10),
		WINDOW_ID(PW_MEMBER11),
		WINDOW_ID(PW_MEMBER12),
		WINDOW_ID(PW_MEMBER13),


	// 외치기
	WINDOW_ID(CHA_CREATEDLG),
		WINDOW_ID(CHA_MSG),
		WINDOW_ID(CHA_CREATEOKBTN),
	WINDOW_ID(CHA_DLG),
		WINDOW_ID(CHA_LIST),

	//
	WINDOW_ID(SEE_CHASEDLG),
		WINDOW_ID(SEE_CHASE_MSG),
		WINDOW_ID(SEE_CHASE_MAP),
		WINDOW_ID(CHASE_SEEOKBTN),
	WINDOW_ID(CHASEDLG),
		WINDOW_ID(CHASE_EDITBOX),
		WINDOW_ID(CHASE_OKBTN),
		WINDOW_ID(CHASE_CANCELBTN),

	//
	WINDOW_ID(CH_NAME_CHANGE_DLG),
		WINDOW_ID(CH_NAME_CHANGE_EDITBOX),
		WINDOW_ID(CH_NAME_CHANGE_OKBTN),
		WINDOW_ID(CH_NAME_CHANGE_CANCELBTN),		

	WINDOW_ID(CH_NAME_CHANGE_OPDLG),
		WINDOW_ID(CH_NAME_CHANGE_STARTBTN),


	// Guild Tournament
	WINDOW_ID(GDT_ENTRYDLG),
		WINDOW_ID(GDT_ENTRY1),		
		WINDOW_ID(GDT_ENTRY2),
		WINDOW_ID(GDT_ENTRYBTN),


	WINDOW_ID(GDT_ENTRYCANCELDLG),
		WINDOW_ID(GDT_CANCELBTN),


	WINDOW_ID(GDT_DLG),
		WINDOW_ID(GDT_MAIN1),
		WINDOW_ID(GDT_MAIN2),
		WINDOW_ID(GDT_SEMIFINAL_PUSHUPBTN),
		WINDOW_ID(GDT_AGROUP_PUSHUPBTN),
		WINDOW_ID(GDT_BGROUP_PUSHUPBTN),
		WINDOW_ID(GDT_CGROUP_PUSHUPBTN),
		WINDOW_ID(GDT_DGROUP_PUSHUPBTN),

		WINDOW_ID(GDT_MAINMARK0),				// 본선
		WINDOW_ID(GDT_MAINMARK1),
		WINDOW_ID(GDT_MAINMARK2),
		WINDOW_ID(GDT_MAINMARK3),
		WINDOW_ID(GDT_MAINMARK4),
		WINDOW_ID(GDT_MAINMENBER1),
		WINDOW_ID(GDT_MAINMENBER2),
		WINDOW_ID(GDT_MAINMENBER3),
		WINDOW_ID(GDT_MAINMENBER4),

		WINDOW_ID(GDT_SECONDMARK0),				// 예선
		WINDOW_ID(GDT_SECONDMARK1),
		WINDOW_ID(GDT_SECONDMARK2),
		WINDOW_ID(GDT_SECONDMARK3),
		WINDOW_ID(GDT_SECONDMARK4),
		WINDOW_ID(GDT_SECONDMARK5),
		WINDOW_ID(GDT_SECONDMARK6),
		WINDOW_ID(GDT_SECONDMARK7),
		WINDOW_ID(GDT_SECONDMARK8),
		WINDOW_ID(GDT_SECONDMEMBER1),
		WINDOW_ID(GDT_SECONDMEMBER2),
		WINDOW_ID(GDT_SECONDMEMBER3),
		WINDOW_ID(GDT_SECONDMEMBER4),
		WINDOW_ID(GDT_SECONDMEMBER5),
		WINDOW_ID(GDT_SECONDMEMBER6),
		WINDOW_ID(GDT_SECONDMEMBER7),
		WINDOW_ID(GDT_SECONDMEMBER8),
		
		WINDOW_ID(GDT_LINE1),				// Line Static
		WINDOW_ID(GDT_LINE2),
		WINDOW_ID(GDT_LINE3),
		WINDOW_ID(GDT_LINE4),
		WINDOW_ID(GDT_LINE5),
		WINDOW_ID(GDT_LINE6),
		WINDOW_ID(GDT_LINE7),
		WINDOW_ID(GDT_LINE8),
		WINDOW_ID(GDT_LINE9),
		WINDOW_ID(GDT_LINE10),
		WINDOW_ID(GDT_LINE11),
		WINDOW_ID(GDT_LINE12),
		WINDOW_ID(GDT_LINE13),
		WINDOW_ID(GDT_LINE14),
		WINDOW_ID(GDT_LINE15),
		WINDOW_ID(GDT_LINE16),
		WINDOW_ID(GDT_LINE17),
		WINDOW_ID(GDT_LINE18),
		WINDOW_ID(GDT_LINE19),
		WINDOW_ID(GDT_LINE20),
		WINDOW_ID(GDT_LINE21),
		WINDOW_ID(GDT_LINE22),
		WINDOW_ID(GDT_LINE23),
		WINDOW_ID(GDT_LINE24),
		WINDOW_ID(GDT_LINE25),
		WINDOW_ID(GDT_LINE26),
		WINDOW_ID(GDT_LINE27),
		WINDOW_ID(GDT_LINE28),
		WINDOW_ID(GDT_LINE29),


	WINDOW_ID(GDT_VIEWDLG),
		WINDOW_ID(GDT_BATTLELIST),
		WINDOW_ID(GDT_WARVIEWBTN),
		WINDOW_ID(GDT_VIEWCANCELBTN),
		

	WINDOW_ID(GDT_COUNTDLG),
		WINDOW_ID(GDT_GTIME),
		WINDOW_ID(GDT_OUTBTN),
		WINDOW_ID(GDT_GUILDNAME1),
		WINDOW_ID(GDT_GUILDMEMBER1),
		WINDOW_ID(GDT_GUILDNAME2),
		WINDOW_ID(GDT_GUILDMEMBER2),
		
	// seigewar
	WINDOW_ID(SW_TIMEREGDLG),
		WINDOW_ID(SW_TIMEREG_TEXT),
		WINDOW_ID(SW_TIME_YEAR),
		WINDOW_ID(SW_TIME_MON),
		WINDOW_ID(SW_TIME_DAY),
		WINDOW_ID(SW_TIME_HOUR),
		WINDOW_ID(SW_TIMEREG_OKBTN),
	WINDOW_ID(SW_PROTECTREGDLG),
		WINDOW_ID(SW_PROTECTREG_LIST),
		WINDOW_ID(SW_PROTECTREG_OKBTN),
	WINDOW_ID(SW_INFODLG),
		WINDOW_ID(SW_DEFENSE_LIST),
		WINDOW_ID(SW_OFFENSE_LIST),
		WINDOW_ID(SW_INFOCLOSEBTN),
	WINDOW_ID(SW_PROFITDLG),
		WINDOW_ID(SW_BACIS_TAX),
		WINDOW_ID(SW_CHANGE_TAX),
		WINDOW_ID(SW_BACIS_MONEY),
		WINDOW_ID(SW_OUT_MONEY),
		WINDOW_ID(SW_TAXCHANGE_OKBTN),
		WINDOW_ID(SW_PROFIT_OKBTN),		
		WINDOW_ID(SW_PROFIT_CANCELBTN),	
	WINDOW_ID(ENGRAVEDLG),
		WINDOW_ID(SW_ENGRAVEGUAGE),
		WINDOW_ID(SW_ENGRAVETIME),
		WINDOW_ID(SW_ENGRAVECANCEL),

	WINDOW_ID(SW_COUNTDLG),
		WINDOW_ID(SW_TIME),
		WINDOW_ID(SWTIME_MUNPA),
		
	WINDOW_ID(SW_STARTTIMEDLG),
		WINDOW_ID(SW_STARTTIME),
		WINDOW_ID(SW_REGTIMESTART),
		WINDOW_ID(SW_REGTIMEEND),
		WINDOW_ID(SW_ADMITTIMESTART),
		WINDOW_ID(SW_ADMITTIMEEND),	
		WINDOW_ID(SW_STARTTIME_OKBTN),

	// Character Change
	WINDOW_ID(CHA_CHANGEDLG),
		WINDOW_ID(CHA_NAME),
		WINDOW_ID(CHA_CharMake),
		WINDOW_ID(CHA_CharCancel),
		WINDOW_ID(CHA_SexType),
		WINDOW_ID(CHA_HairType),
		WINDOW_ID(CHA_FaceType),
		WINDOW_ID(CHA_SexType1),
		WINDOW_ID(CHA_SexType2),
		WINDOW_ID(CHA_HairType1),
		WINDOW_ID(CHA_HairType2),
		WINDOW_ID(CHA_FaceType1),
		WINDOW_ID(CHA_FaceType2),
		WINDOW_ID(CHA_Height),
		WINDOW_ID(CHA_Width),
		
		
	//
	WINDOW_ID(ITEM_LOCKDLG),
		WINDOW_ID(IT_LOCKICON),
		WINDOW_ID(IT_LOCKOKBTN),
		WINDOW_ID(IT_LOCKCANCERBTN),
	
		
	//
	WINDOW_ID(CHANGEJOBDLG),
		WINDOW_ID(CJOB_OKBTN),
		WINDOW_ID(CJOB_CANCELBTN),

	// 강화초기화
	WINDOW_ID(RF_DefaultDLG),
		WINDOW_ID(RF_DefaultICON),
		WINDOW_ID(RF_DefaultOKBTN),
		WINDOW_ID(RF_DefaultCANCERBTN),

	// 축복의 돌
	WINDOW_ID(RareCreateDLG),
		WINDOW_ID(RareCreate_ICON),
		WINDOW_ID(RareCreate_OKBTN),
		WINDOW_ID(RareCreate_CANCERBTN),

 	//SW051129 Pet
		WINDOW_ID(PS_DIALOG),
		WINDOW_ID(PS_SHEET1),			
		WINDOW_ID(PS_SHEET2),			
		WINDOW_ID(PS_LOCK_BTN),			// 펫봉인
		WINDOW_ID(PS_USEREST_BTN),		// 펫활동/휴식
		WINDOW_ID(PS_INVEN_BTN),		// 펫인벤토리
		WINDOW_ID(PS_TOGGLE_S_BTN),		// 펫상태창토글
		WINDOW_ID(PS_NAME),				// 펫이름
		WINDOW_ID(PS_GRADE),			// 펫단계
		WINDOW_ID(PS_STATE),			// 펫휴식
		WINDOW_ID(PS_IMAGE),			// 펫그림
		WINDOW_ID(PS_GUAGE1),			// 펫친밀도
		WINDOW_ID(PS_GUAGE2),			// 펫스테미나
		//WINDOW_ID(PS_GUAGE3),			// 펫스킬
		WINDOW_ID(PS_GUAGETEXT1),		// "친밀도%d"
		WINDOW_ID(PS_GUAGETEXT2),		// "스테미나%d"
		WINDOW_ID(PS_INVENNUM),			// 펫상태창토글
		WINDOW_ID(PS_SKILL1),			// 펫상태창토글
		WINDOW_ID(PS_SKILL2),			// 펫상태창토글
		WINDOW_ID(PS_SKILL3),			// 펫상태창토글
	
		WINDOW_ID(PSMN_DIALOG),
		WINDOW_ID(PSMN_USEREST_BTN),		// 펫활동/휴식
		WINDOW_ID(PSMN_INVEN_BTN),		// 펫인벤토리
		WINDOW_ID(PSMN_NAME),
		WINDOW_ID(PSMN_STATE),			// 펫상태 "휴식/사용%s"
		WINDOW_ID(PSMN_GUAGE1),			// 펫친밀도
		WINDOW_ID(PSMN_GUAGE2),			// 펫스테미나
		//WINDOW_ID(PSMN_GUAGE3),			// 펫스킬
		WINDOW_ID(PSMN_GUAGETEXT1),		// "친밀도%d"
		WINDOW_ID(PSMN_GUAGETEXT2),		// "스테미나%d"
		WINDOW_ID(PSMN_TOGGLE_B_BTN),	// 펫상태창토글

		WINDOW_ID(PET_INVENTORYDLG),	
		WINDOW_ID(PET_WEAREDDLG),		// 펫장비창
		WINDOW_ID(PET_TABBTN1),			// 인벤탭
		WINDOW_ID(PET_TABBTN2),
		WINDOW_ID(PET_TABBTN3),
		WINDOW_ID(PET_TABDLG1),			// 탭그리드
		WINDOW_ID(PET_TABDLG2),
		WINDOW_ID(PET_TABDLG3),

		WINDOW_ID(PetUpgrade_DLG),
		WINDOW_ID(PU_UPGRADE2),			//펫진화단계표시
		WINDOW_ID(PU_UPGRADE3),
		WINDOW_ID(PetUpgrade_ICON),
		WINDOW_ID(PetUpgrade_OKBTN),
		WINDOW_ID(PetUpgrade_CANCERBTN),

		WINDOW_ID(PetRevival_DLG),
		WINDOW_ID(Pet_Revival_ICON),
		WINDOW_ID(PetRevival_OKBTN),
		WINDOW_ID(PetRevival_CANCERBTN),
		WINDOW_ID(PR_GRADE1),
		WINDOW_ID(PR_GRADE2),
		WINDOW_ID(PR_GRADE3),

	// 06. 02. 강화 재료 안내 인터페이스 추가 - 이영준
	WINDOW_ID(RFDGUIDE_DLG),
	WINDOW_ID(RFDG_BTN1),
	WINDOW_ID(RFDG_BTN2),
	WINDOW_ID(RFDG_BTN3),
	WINDOW_ID(RFDG_BTN4),
	WINDOW_ID(RFDG_BTN5),
	WINDOW_ID(RFDG_BTN6),
	WINDOW_ID(RFDG_BTN7),
	WINDOW_ID(RFDG_BTN8),
	WINDOW_ID(RFDG_BTN9),
	WINDOW_ID(GUIDE_SHEET1),
	WINDOW_ID(GUIDE_SHEET2),
	WINDOW_ID(GUIDE_SHEET3),
	WINDOW_ID(GUIDE_SHEET4),
	WINDOW_ID(GUIDE_SHEET5),
	WINDOW_ID(GUIDE_SHEET6),
	WINDOW_ID(GUIDE_SHEET7),
	WINDOW_ID(RFDGUIDE_OKBTN),

	WINDOW_ID(KS_DIALOG),

	WINDOW_ID(GUILDNOTE_DLG),
	WINDOW_ID(GN_TEXTREA),
	WINDOW_ID(GN_SENDOKBTN),
	WINDOW_ID(GN_CANCELBTN),

	WINDOW_ID(ALLYNOTE_DLG),
	WINDOW_ID(AN_TEXTREA),
	WINDOW_ID(AN_SENDOKBTN),
	WINDOW_ID(AN_CANCELBTN),

	// 06. 03. 문파공지 - 이영준
	WINDOW_ID(GUILDNOTICE_DLG),
	WINDOW_ID(GNotice_TEXTREA),
	WINDOW_ID(GNotice_SENDOKBTN),
	WINDOW_ID(GNotice_CANCELBTN),

	
	
	//////////////////////////////////////////////////////////////////
	// 06. 06. 2차 전직 - 이영준
	// 무공 변환
	// 변환창
	WINDOW_ID(SkillTransDLG),
	WINDOW_ID(ST_ICON1),
	WINDOW_ID(ST_ICON2),
	WINDOW_ID(SkillTrans_OKBTN),
	WINDOW_ID(SkillTrans_CANCERBTN),
	WINDOW_ID(SkillTrans_ItemView),
	WINDOW_ID(ST_Option1),
	WINDOW_ID(ST_Option2),
	WINDOW_ID(ST_Option3),
	WINDOW_ID(ST_Option4),
	WINDOW_ID(ST_Option5),
	// 초기화창
	WINDOW_ID(T_DefaultDLG),
	WINDOW_ID(T_DefaultICON),
	WINDOW_ID(T_DefaultOKBTN),
	WINDOW_ID(T_DefaultCANCERBTN),

	//SW060713 문하생
	WINDOW_ID(JOIN_OPTIONDLG),
	WINDOW_ID(JO_CANCELBTN),
	WINDOW_ID(JO_MEMBERBTN),
	WINDOW_ID(JO_STUDENTBTN),

	// 문하생관련 문파소개창
	WINDOW_ID(GU_DLG),
		WINDOW_ID(GU_CHK1),
		WINDOW_ID(GU_CHK2),
		WINDOW_ID(GU_CHK3),
		WINDOW_ID(GU_CHK4),
		//WINDOW_ID(GU_RANK1),
		//WINDOW_ID(GU_RANK2),
		//WINDOW_ID(GU_RANK3),
		//WINDOW_ID(GU_RANK4),
		WINDOW_ID(GU_NUMBER1),
		WINDOW_ID(GU_NUMBER2),
		WINDOW_ID(GU_NUMBER3),
		WINDOW_ID(GU_NUMBER4),
		WINDOW_ID(GU_MARK1),
		WINDOW_ID(GU_MARK2),
		WINDOW_ID(GU_MARK3),
		WINDOW_ID(GU_MARK4),
		WINDOW_ID(GU_NAME1),
		WINDOW_ID(GU_NAME2),
		WINDOW_ID(GU_NAME3),
		WINDOW_ID(GU_NAME4),
		WINDOW_ID(GU_BOOK1),
		WINDOW_ID(GU_BOOK2),
		WINDOW_ID(GU_BOOK3),
		WINDOW_ID(GU_BOOK4),
		WINDOW_ID(GU_SEARCH1LISTBTN),
		WINDOW_ID(GU_SEARCH2LISTBTN),
		WINDOW_ID(GU_SEARCH3LISTBTN),
		WINDOW_ID(GU_SEARCH4LISTBTN),
		WINDOW_ID(GU_SEARCH5LISTBTN),
		WINDOW_ID(GU_CHANGEBTN),
		WINDOW_ID(GU_OKBTN),
		WINDOW_ID(GU_SEARCHFRONTLISTBTN),
		WINDOW_ID(GU_SEARCHBACKLISTBTN),
		WINDOW_ID(GU_lock1),
		WINDOW_ID(GU_lock2),
		WINDOW_ID(GU_lock3),
		WINDOW_ID(GU_lock4),

	//magi82 - 문하생 가입편리시스템 /////////////////////////////////////////
	WINDOW_ID(GT_INFODLG),
		WINDOW_ID(GT_MUNHALIST),
		WINDOW_ID(GT_MUNHA_NUMBERLIST),
		WINDOW_ID(GT_OKBTN),
		WINDOW_ID(GT_CANCERBTN),
		WINDOW_ID(GT_INFOCLOSEBTN),
	//////////////////////////////////////////////////////////////////////////	

	//SW061019 서바이벌모드
	WINDOW_ID(SVV_SURVCOUNTERDLG),
	WINDOW_ID(SVV_ALIVECOUNTER),
	WINDOW_ID(SVV_WINNERNAME),

	// magi82(42) - 샵아이템 추가(수련치 초기화)
	WINDOW_ID(SK_POINT_RESETDLG),
		WINDOW_ID(SK_POINT_RESETBTN),
		WINDOW_ID(SK_POINT_OKBTN),
		WINDOW_ID(SK_POINT_RESET1BTN),
		WINDOW_ID(SK_POINT_RESET2BTN),
		WINDOW_ID(SK_POINT_RESET3BTN),
		WINDOW_ID(SK_POINT_ICONGRID1),
		WINDOW_ID(SK_POINT_ICONGRID2),
		WINDOW_ID(SK_POINT_ICONGRID3),

	// AutoNote
	WINDOW_ID(AND_DLG),
		WINDOW_ID(AND_TEXTAREA_MANUAL),
		WINDOW_ID(AND_BTN_ASK),
		WINDOW_ID(AND_LIST_AUTO),

	WINDOW_ID(ASD_DLG),
		WINDOW_ID(ASD_TEXTAREA_DESC),
		WINDOW_ID(ASD_STC_QUESTION),
		WINDOW_ID(ASD_STC_ANSWER),
		WINDOW_ID(ASD_STC_TIME),
		WINDOW_ID(ASD_BTN_COLOR1),
		WINDOW_ID(ASD_BTN_COLOR2),
		WINDOW_ID(ASD_BTN_COLOR3),
		WINDOW_ID(ASD_BTN_COLOR4),

	// 요새전
	WINDOW_ID(FW_ENGRAVEDLG),
		WINDOW_ID(FW_ENGRAVEGUAGE),
		WINDOW_ID(FW_ENGRAVETIME),
		WINDOW_ID(FW_ENGRAVECANCEL),
	WINDOW_ID(FW_TIMEDLG),
		WINDOW_ID(FW_TIME),
		WINDOW_ID(FW_TIME_CHARACTER),
	WINDOW_ID(FW_WAREHOUSEDLG),
		WINDOW_ID(FW_MONEY),
		WINDOW_ID(FW_PUTOUTMONEYBTN),
		WINDOW_ID(FW_WAREHOUSE1BTN),
		WINDOW_ID(FW_WAREHOUSE2BTN),
		WINDOW_ID(FW_WAREHOUSE3BTN),
		WINDOW_ID(FW_TABDLG1),
		WINDOW_ID(FW_TABDLG2),
		WINDOW_ID(FW_TABDLG3),
	

	//////////////////////////////////////////////////////////////////
////////////////////
// ¸Þ¼¼Ao¹U½º ¾ÆAIμð
	WINDOW_ID(MAX_SCRIPT_ID),
	WINDOW_ID_DEFINE(MBI_OK,IG_MSGBOX_STRARTINDEX),
	WINDOW_ID(MBI_YES),
	WINDOW_ID(MBI_NO),
	WINDOW_ID(MBI_CANCEL),
//-----------------------------------------------
	WINDOW_ID(MBI_NOBTNMSGBOX),	//-->ⓒoY￥ia¨oA CNⓒoⓒª￠￢￠￢ ¡ic￠?eCIAU. CNE¡ⓒ￠￢e￠?￠® ￠￢i¡Æⓒø ￠Oⓒ￢￠￥A¡ÆI ¨uE￥iE.
	WINDOW_ID(MBI_EXIT),
	WINDOW_ID(MBI_PASSERROR),
	WINDOW_ID(MBI_OTHERUSER_CONNECTTRY),
	WINDOW_ID(MBI_DISCONNECTED_OVERLAPPEDLOGIN),
	WINDOW_ID(MBI_SEND_DISCONNECT_OVERLAPPEDLOGIN),
	WINDOW_ID(MBI_VERCHKERROR),
	
	WINDOW_ID(MBI_PARTYBREAKUP),
	
	WINDOW_ID(MBI_PYOGUKBUY),

	WINDOW_ID(MBI_MUGONGDELETE),
	WINDOW_ID(MBI_MUGONGDELETE2),
	WINDOW_ID(MBI_MUGONGDELETE3),
	
	WINDOW_ID(MBI_EXCHANGEAPPLY),
	WINDOW_ID(MBI_EXCHANGEWAITING),
	
	WINDOW_ID(MBI_FRIEND_ADD),
	WINDOW_ID(MBI_PARTY_SECEDE),
	
//------------------------------------------------- LBS A¡¤¡Æ￠® 03.09.17
	WINDOW_ID(MBI_MAKESTREETSTALL),
	WINDOW_ID(MBI_BUYREG),

// LBS 03.10.09 ￠￢¨­¨u¨uAo ⓒoU¨o¨￢ ANd￠￢￠c ¨oAAU//////////////////////////////
	WINDOW_ID(MBI_SELECTLOGINPOINT),	// ¡¤I¡¾¡¿AI ¨¡¡AAI¨¡￠c AuAa
	WINDOW_ID(MBI_LOGINEDITCHECK),
	WINDOW_ID(MBI_DELETEICONCHECK),
	WINDOW_ID(MBI_CHARSELERROR),
	WINDOW_ID(MBI_DELETECHAR),
	WINDOW_ID(MBI_DELETECHARFAIL),
	WINDOW_ID(MBI_CHARMAKEERROR),
	WINDOW_ID(MBI_VIMUAPPLY),
	WINDOW_ID(MBI_VIMUWAITING),
	WINDOW_ID(MBI_MAPCHANGE),			// ￠￢EA¨uAIAo
	WINDOW_ID(MBI_STREETBUYMSG),
	WINDOW_ID(MBI_STREETSELLMSG),
	WINDOW_ID(MBI_REGEDITMSG),
	WINDOW_ID(MBI_QUESTGIVEUP),
	WINDOW_ID(MBI_BAILNOTICEMSG),
	WINDOW_ID(MBI_BAILNOTICEERR),
	WINDOW_ID(MBI_BAILLOWBADFAME),

	WINDOW_ID(MBI_QUESTSTART),			// Item Use¨oA Au¨o¨￢¨¡￠c ¨oAAU
	WINDOW_ID(MBI_QUEST_NONE),		// Item Use¨oA AIⓒoI Au¨o¨￢¨¡￠c ¨oAAU￥iC¨uu=...
	WINDOW_ID(MBI_QUEST_FULL),		// 퀘스트 개수 꽉참(08/01/29)
	
	WINDOW_ID(MBI_OVERLAPPEDLOGIN),
	WINDOW_ID(MBI_OVERLAPPEDLOGININOTHERSERVER),
	WINDOW_ID(MBI_LOGINERRORCLOSE),
	WINDOW_ID(MBI_MAPSERVER_CLOSE),		//￠￢E¨u¡ⓒⓒoi¨￢¨ui¡¾¡¤?
	WINDOW_ID(MBI_SERVERDISCONNECT),	//¨u¡ⓒⓒoob¨uO ⓒ÷¡A¡¾e
	WINDOW_ID(MBI_SELLITEM),//¨u¨¡AIAU¨¡E¡¾a E￠cAI
	WINDOW_ID(MBI_BUYITEM),				//¨u¨¡AIAU¨¡E¡¾a E￠cAI
	WINDOW_ID(MBI_PKMODE),				//PK￠￢ⓒ￡￥ia AuE?

	WINDOW_ID(MBI_NOT_GM),				//GMTOOL IP ¨￢OAIA￠®
	WINDOW_ID(MBI_WAIT_LOGINCHECK),
	WINDOW_ID(MBI_TIMEOVER_TOCONNECT),
	WINDOW_ID(MBI_DISTCONNECT_ERROR),	//Ae½AError·I Distribute¿I ¿￢°aAI ²÷±e.
	WINDOW_ID(MBI_CANTUSEDYNAMIC),		//
	WINDOW_ID(MBI_DYNAMICERROR),		//

	WINDOW_ID(MBI_MPNOTICE_NOTFIT),		//¼o·AAa μi·ICI·A´A ¹≪°øAI AaAø¹≪±a¿I ¸AAo ¾EA½
	WINDOW_ID(MBI_MPNOTICE_SUCCESS),		//¼o·AAa ¼º°ø
	WINDOW_ID(MBI_MPNOTICE_FAIL),		//¼o·AAa ½CÆÐ
	

	WINDOW_ID(MBI_GUILD_SECEDE),		//±æμa A≫Að
	WINDOW_ID(MBI_GUILD_BREAKUP),		//±æμa CØA¼
	WINDOW_ID(MBI_GUILD_BAN),		//±æμa A|¸i
	WINDOW_ID(MBI_GUILD_UNION_DESTROY),	
	WINDOW_ID(MBI_GUILD_UNION_INVITE),	
	WINDOW_ID(MBI_GUILD_UNION_REMOVE),

	WINDOW_ID(MBI_SHOPITEM_LOCK),		// 아이템몰 아이템 봉인해제
	WINDOW_ID(MBI_SAVEDPOINTMOVE),		// 저장포인트로 이동
	WINDOW_ID(MBI_SAVEDPOINTDEL),		// 저장포인트 삭제
	WINDOW_ID(MBI_OTHERREVIVE),			// 부활주문서 사용
	WINDOW_ID(MBI_REVIVECONFIRM),		// 부활할지 확인

	WINDOW_ID(MBI_GUILDFIELDWAR_DECLARE_ACCEPT),
	WINDOW_ID(MBI_GUILDFIELDWAR_DECLARE_DENY),
	WINDOW_ID(MBI_GUILDFIELDWAR_CONFIRM),
	WINDOW_ID(MBI_GUILDFIELDWAR_SUGGEST),
	WINDOW_ID(MBI_GUILDFIELDWAR_SURREND),
	WINDOW_ID(MBI_GUILDFIELDWAR_SUGGEST_ACCEPTDENY),

	WINDOW_ID(MBI_PARTYWAR_SUGGEST),
/////////////////////////////////////////////////////////////////////

	WINDOW_ID(MBI_SKPOINTREDIST_USE),
	WINDOW_ID(MBI_SKPOINTREDIST_UP),
	WINDOW_ID(MBI_SKPOINTREDIST_DOWN),

	WINDOW_ID(MBI_PRESENT_NOTIFY),

	WINDOW_ID(MBI_SHOUT_ACK),
	WINDOW_ID(MBI_SHOUT_NACK),
	WINDOW_ID(MBI_CHASE_NACK),
	WINDOW_ID(MBI_CHANGENAME_ACK),
	WINDOW_ID(MBI_JOBCHANGE_ACK),

	
	WINDOW_ID(MBI_WANTBUY),
	WINDOW_ID(MBI_WANTGIVEUP),

	//magi82 - 문하생 가입편리시스템 /////////////////////////////////////////
    WINDOW_ID(MBI_MUNPAINFODELETE),
	WINDOW_ID(MBI_MUNPAJOIN),
	WINDOW_ID(MBI_MUNPADELETESEL),	// magi82 - 문하생관련(070124)
	//////////////////////////////////////////////////////////////////////////

	// Guild Tournament
	WINDOW_ID(MBI_GTREGIST_SYN),
	WINDOW_ID(MBI_GTREGIST_ACK),
	WINDOW_ID(MBI_GTREGIST_NACK),
	WINDOW_ID(MBI_GTREGISTCANCEL_SYN),
	WINDOW_ID(MBI_GTREGISTCANCEL_ACK),
	WINDOW_ID(MBI_GTREGISTCANCEL_NACK),
	WINDOW_ID(MBI_GTBATTLELIST_OBSERVER),
	WINDOW_ID(MBI_GTSCORE_EXIT),

	///////////////////////////////////////////
	// 06. 06. 2차 전직 - 이영준
	// 무공변환
	WINDOW_ID(MBI_SKILLOPTIONCLEAR_ACK),
	WINDOW_ID(MBI_SKILLOPTIONCLEAR_NACK),
	///////////////////////////////////////////

	WINDOW_ID(MBI_QUESTMSG),

	//SW061207 풀인벤 경고
	WINDOW_ID(MBI_INVEN_FULL_ALERT),
	WINDOW_ID(MBI_SHOPINVEN_FULL_ALERT),

	//SW070103 문파포인트개선
	WINDOW_ID(MBI_GUILD_STUDENTLVUP_CERABRATIONMONEY_MASTERCHECK),

	WINDOW_ID(MBI_ACTION_PENALTY),
	
	WINDOW_ID(MBI_BUDDY_INFOAGREE),
	WINDOW_ID(MBI_BUDDY_NAMECER),

	// magi82(41) - 샵아이템 추가(스텟 초기화 주문서)
	WINDOW_ID(MBI_STATUS_POINT_RESET),
	// magi82(42) - 샵아이템 추가(수련치 초기화)
	WINDOW_ID(MBI_SKILL_POINT_RESET),
	WINDOW_ID(MBI_SKILL_POINT_RESET_FAIL),

//------- DIVIDEBOX￠?￠®¨u¡ⓒ ¡ic￠?e
	WINDOW_ID(DBOX_DIVIDE_INV),
	WINDOW_ID(DBOX_DIVIDE_STREETSTALL),
	WINDOW_ID(DBOX_DIVIDE_STREETBUYSTALL),
	WINDOW_ID(DBOX_SELL),
	WINDOW_ID(DBOX_BUY),
	WINDOW_ID(DBOX_INPUT_MONEY),
	WINDOW_ID(DBOX_EXCHANGE_MONEY),
	

// GAMEIN￠?￠®¨u¡ⓒ ¡ic￠?eCI￠￥A Enum ////////////////////////////////////////////////////////////
/*DebugDlg*/		
	WINDOW_ID_DEFINE(DI_DEBUGDLG,IG_DEBUG_START),
	WINDOW_ID(DI_DEBUGCHAT), 
	WINDOW_ID(DI_DEBUGATTACK), 
	WINDOW_ID(DI_DEBUGMUGONG), 
	WINDOW_ID(DI_DEBUGMOVE), 
	WINDOW_ID(DI_DEBUGITEM), 
	WINDOW_ID(DI_DEBUGUSERCONN),
////////////////////////////////////////////////////////////////////////////////////////

	// siegewar
	WINDOW_ID(MBI_SW_PROTECTREG_OK),
	WINDOW_ID(MBI_SW_TAXCHANGE_OK),
	WINDOW_ID(MBI_SW_PROFIT_OK),
	WINDOW_ID(MBI_GUILD_CHANGE_LOCATION),

	WINDOW_ID(MBI_SW_ENGRAVE_SYN),
	WINDOW_ID(MBI_SW_PROPOSAL_SYN),
	WINDOW_ID(MBI_SW_ATTACKREGIST_SYN),
	WINDOW_ID(MBI_SW_OBSERVER_SYN),

	WINDOW_ID(MBI_TITAN_REPAIR),	// magi82 - Titan(070511)
	WINDOW_ID(MBI_TITAN_TOTAL_REPAIR),	// magi82 - Titan(070515)

	WINDOW_ID(MBI_SOS),	// magi82 - SOS(070720)
	WINDOW_ID(MBI_SOS_YES),	// magi82 - SOS(070724)

	//스크린샷
	WINDOW_ID(SC_STC_TIME), //스태틱(시간)
	WINDOW_ID(SC_MAINDLG), //다이얼로그	

	WINDOW_ID(MBI_FT_ENGRAVE_START_SYN),	// 요새전 각인
	WINDOW_ID(MBI_FT_ITEM_MOVE_SYN),		// 요새창고에서 인벤토리로 아이템 이동시
	WINDOW_ID(MBI_FT_MONEY_MOVE_SYN),		// 요새창고에서 인벤토리로 돈 이동시

	WINDOW_ID(MAX_IDENUM),
/////////////////////////////////////////////////////////////////////////////////////////////////////
