#ifndef PARSER_H
#define PARSER_H


#define PID_STATIC_MODEL	"STATIC_MODEL"
#define PID_HEIGHT_FIELD	"HEIGHT_FIELD"
#define PID_GX_MAP			"GX_MAP"
#define PID_GX_OBJECT		"GX_OBJECT"
#define PID_GX_LIGHT		"GX_LIGHT"
#define PID_GX_TRIGGER		"GX_TRIGGER"
#define PID_PRELOAD_GXOBJECT "PRELOAD_GXOBJECT"



#endif
