//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 4DyuchiGXMapEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW_BOTTOM             101
#define IDR_MODELVIEW_TMPL              103
#define IDR_MODELVIEW_TMPL1             106
#define IDD_LEFPANE_FORM                107
#define IDR_LEFPANE_TMPL                108
#define IDR_BOTTOMPANE_TMPL             109
#define IDR_LEFTPANE_TMPL               110
#define IDR_MAINFRAME                   128
#define IDD_DLGBAR_PANEL1               128
#define IDR_MY4DYUTYPE                  129
#define IDD_DIALOG1                     130
#define IDD_DIALOG_HFIELD_BOARD         131
#define IDD_DIALOG_CONSOLE              132
#define IDD_DIALOG_MODEL_VIEW           134
#define IDD_DIALOG_HFIELD_PROPERTY      135
#define IDD_DLG_BAR2                    136
#define IDD_DLGBAR_PANEL2               137
#define IDD_DLGBAR_STATUS               138
#define IDD_DIALOG_LIGHT_PROPERTY       139
#define IDD_DIALOG_BRUSH_MANAGE         140
#define IDD_FORMVIEW_RIGHT              141
#define IDD_DIALOG_OBJECT_PROPERTY      143
#define IDD_DIALOG_TRIGGER_PROPERTY     144
#define IDR_POPUP                       146
#define IDD_NPC_INFO                    147
#define IDD_SECTION_INFO                148
#define IDB_BITMAP_PICK                 150
#define IDD_DIALOG_TILEBRUSH_PROPERTY   151
#define IDD_DIALOG2                     152
#define IDD_DIALOG_DIRECTIONAL_LIGHT    153
#define IDD_DIALOG3                     154
#define IDB_BITMAP_PICK_COLOR           158
#define IDD_DIALOG4                     159
#define IDR_POPUP_HFIELD_ALPHAMAP       164
#define IDD_EDITTILEENTRY               165
#define IDD_TILESET                     166
#define IDD_TILESETEDIT                 167
#define IDD_LOADFAILEDTEXTURE_DIALOG_   168
#define IDC_LIST_TILE_VIEW              1001
#define IDC_BUTTON_LOAD_PALETTE         1002
#define IDC_SCROLLBAR1                  1003
#define IDC_SCROLLBAR2                  1004
#define IDC_BUTTON_REFRESH              1005
#define IDC_LIST_HFIELD_BOARD           1006
#define IDC_SCROLLBAR_V_HFIELD_BOARD    1007
#define IDC_SCROLLBAR_H_HFIELD_BOARD    1008
#define IDC_BUTTON_HFIELD_BOARD_REFRESH 1009
#define IDC_EDIT1                       1010
#define IDC_EDIT_G                      1011
#define IDC_EDIT_BACK_GREEN             1011
#define IDC_LIST_TILE_PALETTE           1012
#define IDC_EDIT_B                      1012
#define IDC_EDIT_BACK_BLUE              1012
#define IDC_LIST_MODEL_VIEW             1013
#define IDC_EDIT_RS                     1013
#define IDC_EDIT_AMBIENT_G              1013
#define IDC_RADIO_EDIT_VERTEX           1014
#define IDC_EDIT_X                      1014
#define IDC_EDIT_AMBIENT_B              1014
#define IDC_RADIO_EDIT_TILE             1015
#define IDC_EDIT_Y                      1015
#define IDC_EDIT_SPECULAR_G             1015
#define IDC_RADIO_RMODE_WIRE            1016
#define IDC_EDIT_Z                      1016
#define IDC_EDIT_SPECULAR_B             1016
#define IDC_RADIO_RMODE_SOLID           1017
#define IDC_BUTTON_REFRESH_MODEL_VIEW   1017
#define IDC_EDIT_UID                    1017
#define IDC_EDIT_DIR_X                  1017
#define IDC_COPY_TO_BRUSH               1018
#define IDC_RADIO_EDIT_BRUSH            1018
#define IDC_EDIT_AXIS_X                 1018
#define IDC_EDIT_DIR_Y                  1018
#define IDC_RADIO_EDIT_GXO              1019
#define IDC_EDIT_AXIS_Y                 1019
#define IDC_EDIT_DIR_Z                  1019
#define IDC_STATIC_AREA                 1020
#define IDC_RADIO_GET_POS_TILE          1020
#define IDC_EDIT_AXIS_Z                 1020
#define IDC_RADIO_GET_HFOBJ             1021
#define IDC_EDIT_RAD                    1021
#define IDC_RADIO_LIGHT_MODE            1022
#define IDC_EDIT_SCALE_X                1022
#define IDC_CHECK_XZ                    1023
#define IDC_RADIO_TRIGGER_MOD           1023
#define IDC_RADIO_TRIGGER_MODE          1023
#define IDC_EDIT_SCALE_Y                1023
#define IDC_RADIO_XAXIS                 1024
#define IDC_EDIT_Z2                     1024
#define IDC_EDIT_SCALE_Z                1024
#define IDC_CHECK_XY                    1025
#define IDC_RADIO_YAXIS                 1025
#define IDC_CHECK_YZ                    1026
#define IDC_RADIO_ZAXIS                 1026
#define IDC_RADIO_MOVE                  1027
#define IDC_RADIO_ROT                   1028
#define IDC_RADIO_SCALE                 1029
#define IDC_BUTTON_RESET_TR             1030
#define IDC_RADIO_HFIELD_ALPHA_MAP      1030
#define IDC_EDIT_LEFT                   1031
#define IDC_RADIO_CREATE                1031
#define IDC_EDIT_RIGHT                  1032
#define IDC_RADIO_DELETE                1032
#define IDC_EDIT_TOP                    1033
#define IDC_RADIO_AXIS_FREE             1033
#define IDC_EDIT_BOTTOM                 1034
#define IDC_RADIO_DRAW_LIGHTMAP         1034
#define IDC_EDIT_FACE_SIZE              1035
#define IDC_RADIO_DRAW_HFIELD_VCOLOR    1035
#define IDC_EDIT_TILE_NUM_PER_OBJ       1036
#define IDC_BUTTON_HFIELD_EX1           1037
#define IDC_EDIT_FACES_NUM_PER_OBJ      1038
#define IDC_EDIT_TILE_SIZE              1039
#define IDC_EDIT_LOW_DETAIL_TEXTURE_SIZE 1040
#define IDC_EDIT_LIGHT_TEXEL_SIZE       1041
#define IDC_EDIT_HFIELD_NAME            1042
#define IDC_BUTTON_HFIELD_EX2           1043
#define IDC_BUTTON_HFIELD_EX3           1044
#define IDC_BUTTON_HFIELD_PROPERTY_OK   1045
#define IDC_BUTTON1                     1046
#define IDC_BUTTON_HFIELD_EX4           1046
#define IDC_BUTTON_RESET_Z              1046
#define IDC_BUTTON_OK                   1046
#define IDC_BUTTON_LOAD_BRUSH_MODEL     1046
#define IDC_BUTTON_LOAD                 1046
#define IDC_BUTTON_FILL_SELECTED_TILE   1046
#define IDC_BUTTON_DIRECTIONAL_LIGHT    1046
#define IDC_SELECTTILE1                 1046
#define IDC_NEW                         1046
#define IDC_ENTRY0                      1046
#define IDC_SAVELIST_BUTTON             1046
#define IDC_EDIT_SAMPLE_STEP            1047
#define IDC_EDIT_DEFAULT_Z              1047
#define IDC_BUTTON_LOAD_GXOBJECT        1047
#define IDC_BUTTON_DELETE               1047
#define IDC_BUTTON_HFIELD_EX5           1047
#define IDC_SELECTTILE2                 1047
#define IDC_SAVE                        1047
#define IDC_ENTRY1                      1047
#define IDC_EDIT_OBNNUM_X               1048
#define IDC_BUTTON_DELETE_BRUSH         1048
#define IDC_SELECTTILE3                 1048
#define IDC_LOAD                        1048
#define IDC_ENTRY2                      1048
#define IDC_EDIT_OBJNUM_Z               1049
#define IDC_STATIC_TOTALTEXMEM          1049
#define IDC_BUTTON_DELETE_GXOBJECT      1049
#define IDC_SELECTTILE4                 1049
#define IDC_ADD                         1049
#define IDC_ENTRY3                      1049
#define IDC_STATIC_AVTEXMEM             1050
#define IDC_EDIT_LOD_NUM                1050
#define IDC_EDIT_AMBIENT_COLOR          1050
#define IDC_BUTTON_SELECT_BRUSH_MODEL   1050
#define IDC_BUTTON_CREATE_BRUSH         1050
#define IDC_DELETE                      1050
#define IDC_ENTRY4                      1050
#define IDC_EDIT_INDEX_BUFFER_NUM       1051
#define IDC_RADIO_CREATE_LIGHT          1051
#define IDC_BUTTON_DELETE_BRUSH_MODEL   1051
#define IDC_BUTTON_DELETE_TILE_BRUSH    1051
#define IDC_STATIC_ALPHAMAP_NUM         1051
#define IDC_Modify                      1051
#define IDC_ENTRY5                      1051
#define IDC_RADIO_CREATE_CUSTOM         1052
#define IDC_EDIT_R                      1052
#define IDC_BUTTON_DELETEALL_TILE_BRUSH 1052
#define IDC_STATIC_ALPHAMAP_MEM_SIZE    1052
#define IDC_ENTRY6                      1052
#define IDC_BUTTON_HFIELD_TTB           1052
#define IDC_RADIO_CREATE_TRIGGER        1053
#define IDC_LIST_BRUSH                  1053
#define IDC_EDIT_MIN_TILE_LENGTH        1053
#define IDC_EDIT_AMBIENT_R              1053
#define IDC_ENTRY7                      1053
#define IDC_BUTTON2                     1054
#define IDC_LIST_GXOBJECT               1054
#define IDC_BUTTON_VIEW_PROPERTY        1054
#define IDC_EDIT_SPECULAR_R             1054
#define IDC_BUTTON_REPLACE_TEXTURE      1054
#define IDC_CHANGEDIRECTION1            1054
#define IDC_ENTRY8                      1054
#define IDC_LIST_TILE_BRUSH             1055
#define IDC_CHANGEDIRECTION2            1055
#define IDC_ENTRY9                      1055
#define IDC_BUTTON_ROTATE_TEXTURE       1056
#define IDC_CHANGEDIRECTION3            1056
#define IDC_ENTRY10                     1056
#define IDC_BUTTON_BRUSH_SELECT         1057
#define IDC_CHANGEDIRECTION4            1057
#define IDC_ENTRY11                     1057
#define IDC_BUTTON_BRUSH_UNSELECT       1058
#define IDC_ENTRY12                     1058
#define IDC_BUTTON_BRUSH_SELECT_GXOBJECT 1059
#define IDC_ENTRY13                     1059
#define IDC_EDIT_SHADE_COLOR_R          1060
#define IDC_EDIT_SHADE_COLOR_G          1061
#define IDC_EDIT_SHADE_COLOR_B          1062
#define IDC_CHECK_ENABLE_SHADOW         1063
#define IDC_BUTTON_SHADE_START          1064
#define IDC_STATIC_TILE_X               1065
#define IDC_STATIC_TILE_Z               1066
#define IDC_EDIT_STATIC_MODEL_ALPHA     1068
#define IDC_EDIT_HFIELD_ALPHA           1069
#define IDC_BUTTON_TRANSPARENCY_SET     1070
#define IDC_EDIT_VIEW_ONLY_HFIELD_ALPHA 1071
#define IDC_EDIT_BRUSH_SIZE             1073
#define IDC_CHECK_ONOFF                 1074
#define IDC_CHECK_SHADOW_ONOFF          1075
#define IDC_CHECK_SELECT                1076
#define IDC_CHECK_ENABLE_DYNAMIC_LIGHT  1076
#define IDC_EDIT_HEIGHT_PITCH           1078
#define IDC_EDIT_INTERPOLATION_BIAS     1079
#define IDC_EDIT_RADIUS                 1080
#define IDC_EDIT_BRUSH_NAME             1082
#define IDC_CHECK_TILE_BRUSH_MODE       1083
#define IDC_LOAD_TILE_BRUSH             1084
#define IDC_SAVE_TILE_BRUSH             1085
#define IDC_CHECK_APPLY_HFIELD          1085
#define IDC_BUTTON_REFRESH_HFIELD       1086
#define IDC_CHECK_AS_EFFECT             1086
#define IDC_EDIT_LIGHT_POS_X            1087
#define IDC_EDIT_LIGHT_POS_Y            1088
#define IDC_CHECK_TRANSFORM_LOCK        1088
#define IDC_EDIT_LIGHT_POS_Z            1089
#define IDC_EDIT_MAX_HEIGHT             1089
#define IDC_EDIT_MIN_HEIGHT             1090
#define IDC_EDIT_HFIELD_DETAIL          1091
#define IDC_BUTTON_HFOBJ_DISABLE        1092
#define IDC_BUTTON_HFOBJ_ENABLE         1093
#define IDC_BUTTON_HFOBJ_FREEZE_DETAIL  1094
#define IDC_BUTTON_HFOBJ_UNFREEZE_DETAIL 1095
#define IDC_EDIT_FREEZE_DETAIL          1096
#define IDC_CHECK_DIRECTIONAL_LIGHT     1097
#define IDC_EDIT_DIFFUSE_R              1098
#define IDC_EDIT_DIFFUSE_G              1099
#define IDC_EDIT_DIFFUSE_B              1100
#define IDC_BUTTON_BACK_MODIFY          1101
#define IDC_EDIT_BACK_RED               1102
#define IDC_EDIT_LM_R                   1103
#define IDC_EDIT_LM_G                   1104
#define IDC_EDIT_LM_B                   1105
#define IDC_STATIC_CURRENT_COLOR        1106
#define IDC_CHECK_PICK_COLOR            1107
#define IDC_STATIC_SHADING_COLOR        1107
#define IDC_EDIT_HFBRUSH_SIZE           1111
#define IDC_RADIO_DRAW_ALPHA_TEXEL      1112
#define IDC_CHECK_HFIELD_BLEND          1114
#define IDC_RADIO_ALPHA_BRUSH_ADD       1115
#define IDC_RADIO_ALPHA_BRUSH_SUB       1116
#define IDC_EDIT_ALPHA_BRUSH_BRIGHT     1117
#define IDC_RADIO_TS                    1118
#define IDC_PROBABILITY1                1119
#define IDC_PROBABILITY2                1120
#define IDC_PROBABILITY3                1121
#define IDC_PROBABILITY4                1122
#define IDC_SHOW                        1123
#define IDC_LIST1                       1126
#define IDC_TILESETNAME                 1127
#define IDC_LOADFAILED_LIST             1142
#define IDC_RADIO_RMODE_BOTH            1143
#define IDC_STATIC_SELECT_TILE_NAME     1144
#define IDC_STATIC_TEXTURE_FILE_NAME    1145
#define IDC_BUTTON_CREATE_NPC           2000
#define IDC_LIST_NPC_INFO               2001
#define IDC_COMBO_NPC_NUM               2002
#define IDC_STATIC_XPOS                 2003
#define IDC_STATIC_ZPOS                 2004
#define IDC_STATIC_SECTION_NUM          2005
#define IDC_STATIC_SECTION_TOP          2006
#define IDC_STATIC_SECTION_LEFT         2007
#define IDC_STATIC_SECTION_RIGHT        2008
#define IDC_STATIC_SECTION_BOTTOM       2009
#define ID_SECTION_DLG_OK               2010
#define IDC_BUTTON_LPOS                 10488
#define ID_NEW_HFIELD                   32771
#define ID_EXPORT_HFIELD                32772
#define ID_IMPORT_HFIELD                32773
#define ID_SAMPLE_FROM_MOD              32774
#define ID_CREATE_STATIC_MODEL_FROM_MOD 32775
#define ID_BUILD_MAP                    32776
#define ID_SHADE_LIGHTMAP               32777
#define ID_TOGGLE_LIGHTMAP              32778
#define ID_IMPORT_MODEL                 32779
#define ID_BEGIN_CREATE_STATIC_MODEL    32780
#define ID_END_CREATE_STATIC_MODEL      32781
#define ID_NEW_STATIC_MODEL             32782
#define ID_EXPORT_STATIC_MODEL          32783
#define ID_IMPORT_STATIC_MODEL          32784
#define ID_INSERT_GXOBJECT              32785
#define ID_VIEW_TILE_PALETTE            32786
#define ID_EXPORT_TILE_TABLE            32787
#define ID_MENU_BOUNDINGBOX             32788
#define ID_IMPORT_MOD_AS_BRUSH          32789
#define ID_NEW_MAP                      32790
#define ID_DELETE_ALL_GXOBJECTS         32791
#define ID_DELETE_ALL_GXLIGHTS          32792
#define ID_SAVE_MAP                     32793
#define ID_LOAD_MAP                     32794
#define ID_SECTION_INPUT                32795
#define ID_SECTION_INFO                 32796
#define ID_CREATE_NPC                   32797
#define ID_LOAD_TTB                     32798
#define ID_CREATE_LIGHT_FROM_MOD        32799
#define ID_SAVE_ALL_LIGHTS              32800
#define ID_LOAD_LIGHTS                  32801
#define ID_CALL_HELP                    32802
#define ID_MENUITEM_HFIELD_PROPERTY_CHANGE 32803
#define ID_LOAD_VIEWONLY_HFIELD         32804
#define ID_VIEW_ONLY_HFIELD             32805
#define ID_MOVESPOT_INPUT               32806
#define ID_MOVESPOT_INFO                32808
#define ID_STARTSPOT_INPUT              32809
#define ID_STARTSPOT_INFO               32810
#define ID_SAVE_TTB                     32811
#define ID_TOGGLE_ONLY_LIGHTTEXTURE     32812
#define ID_SAVE_ALL_GXOBJECTS           32813
#define ID_LOAD_GXOBJECTS               32814
#define ID_VIEW_COLLISION_STM           32815
#define ID_MENUITEM_CLEAR_ALPHAMAP      32816
#define ID_MENUITEM_CLEAR_ALPHAMAP_TILEINDEX 32817
#define ID_MENUITEM_CLEAR_ALPHAMAP_OBJECT 32818
#define ID_VIEW_TILESET                 32819
#define ID_VIEW_CAMERA_INFO             32820
#define ID_VIEW_LOAD_FAILED_TEXTURE_LIST 32821
#define ID_VIEW_TOGGLE_TOOL_OBJECT      32823
#define ID_VIEW_RENDER_STATIC_MODEL     32824
#define ID_ACCELERATOR_PICKER           32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1146
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
