//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ModelView.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DIALOGBAR                   103
#define IDR_MAINFRAME                   128
#define IDR_MODELVTYPE                  129
#define IDR_TOOLBAR                     138
#define IDD_FRAME_SPEED_DIALOG          141
#define IDD_LIGHT_DIALOG                142
#define IDD_SPECULAR                    143
#define IDD_SPECULAR_DIALOG             143
#define IDD_ILLUSION_ATTACH_DIALOG      144
#define IDD_ILLUSION_SETUP              145
#define IDD_SET_BACKGROUND_COLOR        147
#define IDD_DIALOG_EFFECTPALETTE        148
#define IDD_DIALOG_CREATE_EFFECT        149
#define IDD_DIALOG_FRONT_OF_CAMERA      151
#define IDC_STATIC_HAHA                 1007
#define IDC_EDIT_FPS                    1008
#define IDC_FPS_OK_BUTTON               1009
#define IDC_EDT_DIF_R                   1011
#define IDC_EDT_DIF_G                   1012
#define IDC_EDT_DIF_B                   1013
#define IDC_EDT_AMB_R                   1014
#define IDC_EDT_AMB_G                   1015
#define IDC_EDT_AMB_B                   1016
#define IDC_DIRECTION_X                 1020
#define IDC_DIRECTION_Z                 1021
#define IDC_DIRECTION_Y                 1022
#define IDC_BUTTON1                     1023
#define IDC_LIGHT_OK_BUTTON             1023
#define IDC_SPEC_SET_OK                 1023
#define IDC_SET_BACKGROUNDCOLOR_DEFAULT 1023
#define IDC_BUTTON_EFFECT_SAVE          1023
#define IDC_BUTTON_EFFECT_NAME_OK       1023
#define IDC_FOC_DISTANCE_BUTTON         1023
#define IDC_LIGHT_CHECK                 1024
#define IDC_BUTTON_EFFECT_LOAD          1024
#define IDC_SCROLLBAR1                  1025
#define IDC_FRAME_SCROLL                1025
#define IDC_BUTTON_EFFECT_DELETE        1025
#define IDC_BUTTON_EFFECT_CREATE        1026
#define IDC_FRAME_STATIC                1027
#define IDC_PLAY_SOUND_CHECK            1028
#define IDC_SPECULAR_ENABLE             1029
#define IDC_BUTTON2                     1030
#define IDC_BUTTON_UPDATE_EFFECT_PALETTE 1030
#define IDC_SPEC_INTENSITY              1031
#define IDC_EDIT_ALPHA                  1032
#define IDC_ILLUSION_MOD_LIST           1033
#define IDC_ILLUSION_OBJECT_LIST        1034
#define IDC_ILLU_DLG_TEXT_MOD           1035
#define IDC_ILLU_DLG_TEXT_OBJECT        1036
#define ID_ILLUMINATION_LOAD_OK         1037
#define ID_ILLUMINATION_DLG_CANCEL      1038
#define IDC_ILLUSION_SETUP_DLG_LENGTH_EDIT 1039
#define IDC_ILLUSION_SETUP_SHOW_CHECK   1040
#define IDC_ILLUSION_SETUP_LENGTH_STATIC 1041
#define IDC_BACKGROUNDCOLOR_R           1042
#define IDC_BACKGROUNDCOLOR_G           1043
#define IDC_BACKGROUNDCOLOR_B           1044
#define IDC_LIST_EFFECT                 1045
#define IDC_CHECK_TEXGEN_WAVE           1047
#define IDC_CHECK_DISABLE_SRCTEX        1048
#define IDC_EDIT_EFFECT_NAME            1049
#define IDC_BUTTON_EFFECT_APPLY         1050
#define IDC_BUTTON_BROWSE_TEXFILE       1051
#define IDC_EDIT_TEX_NAME               1053
#define IDC_STATIC_PICK_OBJNAME         1054
#define IDC_FOC_CURRENT_OBJECT_STATIC   1056
#define IDC_FOC_BROWSE_BUTTON           1057
#define IDC_FOC_ALPHA_EDIT              1059
#define IDC_FOC_ALPHA_BUTTON            1060
#define IDC_FOC_REMOVE_BUTTON           1061
#define IDC_FOC_DISTANCE_EDIT           1062
#define IDC_COMBO1                      32772
#define IDC_SCROLL                      32773
#define IDC_COMBO2                      32774
#define IDC_PLAY_BUTTON                 32775
#define IDC_STOP_BUTTON                 32776
#define IDC_STATIC_FRAME                32777
#define ID_OPEN_MOD                     32777
#define ID_OPEN_ANM                     32778
#define ID_CLOSE_MOD                    32779
#define ID_CLOSE_ANM                    32780
#define ID_OEPN_CH_FILE                 32781
#define ID_EXPORT_CHR                   32783
#define IDC_RESET_CAMERA                32784
#define IDC_ALL_SELECT                  32785
#define IDC_SET_FRAME                   32786
#define IDC_LIGHT_DIALOG                32788
#define ID_OPEN_MTL                     32789
#define ID_CLOSE_MTL                    32790
#define IDC_COMBO3                      32791
#define IDC_SELECT_ALL_MOD              32792
#define IDC_GRID_DISPLAY                32793
#define IDC_BOUNDING_DRAW               32794
#define IDC_BONE_BOUNDING_DRAW          32795
#define IDM_WIREMODE                    32796
#define ID_RENDER_CAMERA_INFO           32797
#define IDC_COMBO4                      32799
#define ID_OPEN_WAV                     32800
#define ID_CLOSE_WAV                    32801
#define ID_WAV_LIST_CLEAR               32802
#define ID_SPECULAR_SETTING             32803
#define IDM_ILLUMINATION_LOAD           32804
#define IDM_ILLUMINATION_UNLOAD         32805
#define IDM_ILLUMINATION_SETUP          32806
#define IDM_SET_BACKGROUND_COLOR        32807
#define ID_VIEW_EFFECT_PALETTE          32808
#define IDC_FRONT_OF_CAMERA             32809
#define IDC_FRONT_OF_CAMERA_STATIC      32810
#define IDM_BOTHMODE                    32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
