#pragma once

enum CHUNK_ID
{
	CHUNK_ID_SCENE,
	CHUNK_ID_GEOMETRY_OBJECT,
	CHUNK_ID_MODELS_LIST,
	CHUNK_ID_MODEL,
	CHUNK_ID_OBJECTS_LIST,
	CHUNK_ID_OBJECT,
	CHUNK_ID_FACES_GROUP_LIST,
	CHUNK_ID_FACES_GROUP,
	CHUNK_ID_FACES_LIST,
	CHUNK_ID_VERTICES_LIST,
};
